/* Phase 3C strictly read-only, all-tenant preflight. Temporary analysis objects only; requires administrative/RLS visibility. No PHI. */
SET NOCOUNT ON;
DECLARE @SessionTenantId sql_variant=SESSION_CONTEXT(N'ShaleClientId');
DECLARE @IsAdministrativePrincipal bit=CONVERT(bit,CASE WHEN ISNULL(IS_SRVROLEMEMBER(N'sysadmin'),0)=1 OR ISNULL(IS_MEMBER(N'db_owner'),0)=1 THEN 1 ELSE 0 END);
DECLARE @OperatorVerifiedAllTenantVisibility bit=0; -- Set to 1 only after the documented independent RLS/inventory verification.
IF OBJECT_ID(N'dbo.Cases',N'U') IS NULL THROW 56000,'Missing dbo.Cases.',1;
IF OBJECT_ID(N'dbo.CaseDates',N'U') IS NULL THROW 56001,'Missing dbo.CaseDates.',1;
IF OBJECT_ID(N'dbo.CaseDateTypes',N'U') IS NULL THROW 56002,'Missing dbo.CaseDateTypes.',1;
IF COL_LENGTH(N'dbo.CaseDates',N'IsDeleted') IS NULL THROW 56003,'Expected dbo.CaseDates.IsDeleted.',1;
DECLARE @DraftAliasDefinitionCount bigint=(SELECT COUNT_BIG(*) FROM dbo.CaseDateTypes WHERE SystemKey=N'medical_negligence_discovered');
DECLARE @DraftAliasOccurrenceCount bigint=(SELECT COUNT_BIG(*) FROM dbo.CaseDates cd JOIN dbo.CaseDateTypes t ON t.Id=cd.CaseDateTypeId WHERE t.SystemKey=N'medical_negligence_discovered');
SELECT SystemKey,Name,CalendarCategory,SupportsTime INTO #ExpectedTypes FROM (VALUES
(N'intake',N'Intake','OTHER',CAST(1 AS bit)),(N'date_of_injury',N'Date of Injury','MILESTONE',CAST(0 AS bit)),(N'date_of_medical_negligence',N'Date of Medical Negligence','MILESTONE',CAST(0 AS bit)),(N'date_medical_negligence_discovered',N'Date Medical Negligence Was Discovered','MILESTONE',CAST(0 AS bit)),
(N'statute_of_limitations',N'Statute of Limitations','DEADLINE',CAST(0 AS bit)),(N'tort_notice_deadline',N'Tort Notice Deadline','NOTICE',CAST(0 AS bit)),(N'discovery_deadline',N'Discovery Deadline','DEADLINE',CAST(0 AS bit)),
(N'fee_agreement_signed',N'Fee Agreement Signed','MILESTONE',CAST(0 AS bit)),(N'non_engagement_letter_sent',N'Non-Engagement Letter Sent','MILESTONE',CAST(0 AS bit)))v(SystemKey,Name,CalendarCategory,SupportsTime);
/* Global seed compatibility is profiled independently of participating tenants and exactly mirrors seed_types.sql rejection rules. */
SELECT e.SystemKey,e.Name ExpectedName,e.CalendarCategory ExpectedCategory,e.SupportsTime ExpectedSupportsTime,COUNT(t.Id) GlobalDefinitionCount,
 SUM(CASE WHEN t.Id IS NOT NULL AND t.Name<>e.Name THEN 1 ELSE 0 END) ExactNameConflictCount,SUM(CASE WHEN t.Id IS NOT NULL AND t.CalendarCategory<>e.CalendarCategory THEN 1 ELSE 0 END) CategoryConflictCount,SUM(CASE WHEN t.Id IS NOT NULL AND t.SupportsTime<>e.SupportsTime THEN 1 ELSE 0 END) SupportsTimeConflictCount,SUM(CASE WHEN t.Id IS NOT NULL AND ISNULL(t.IsActive,0)<>1 THEN 1 ELSE 0 END) InactiveCount,SUM(CASE WHEN t.Id IS NOT NULL AND ISNULL(t.IsDeleted,0)<>0 THEN 1 ELSE 0 END) DeletedCount
INTO #GlobalSeedProfile FROM #ExpectedTypes e LEFT JOIN dbo.CaseDateTypes t ON t.ShaleClientId IS NULL AND t.SystemKey=e.SystemKey GROUP BY e.SystemKey,e.Name,e.CalendarCategory,e.SupportsTime;
SELECT c.ShaleClientId,c.Id CaseId,v.FieldName,v.SystemKey,
 CASE WHEN v.FieldName='CallerDate' AND c.CallerTime IS NOT NULL THEN DATETIME2FROMPARTS(DATEPART(year,c.CallerDate),DATEPART(month,c.CallerDate),DATEPART(day,c.CallerDate),DATEPART(hour,CAST(c.CallerTime AS time)),DATEPART(minute,CAST(c.CallerTime AS time)),DATEPART(second,CAST(c.CallerTime AS time)),DATEPART(nanosecond,CAST(c.CallerTime AS time))/100,7) ELSE CAST(v.LegacyDate AS datetime2(7)) END ExpectedStartsAt,
 CAST(CASE WHEN v.FieldName='CallerDate' AND c.CallerTime IS NOT NULL THEN 0 ELSE 1 END AS bit) ExpectedAllDay
INTO #LegacyCaseDateSources FROM dbo.Cases c CROSS APPLY(VALUES
 ('CallerDate','intake',c.CallerDate),('DateOfMedicalNegligence','date_of_medical_negligence',c.DateOfMedicalNegligence),('DateMedicalNegligenceWasDiscovered','date_medical_negligence_discovered',c.DateMedicalNegligenceWasDiscovered),('DateOfInjury','date_of_injury',c.DateOfInjury),('StatuteOfLimitations','statute_of_limitations',c.StatuteOfLimitations),('TortNoticeDeadline','tort_notice_deadline',c.TortNoticeDeadline),('DiscoveryDeadline','discovery_deadline',c.DiscoveryDeadline),('DateFeeAgreementSigned','fee_agreement_signed',c.DateFeeAgreementSigned),('DateNonEngagementLetterSent','non_engagement_letter_sent',c.DateNonEngagementLetterSent)
) v(FieldName,SystemKey,LegacyDate) WHERE v.LegacyDate IS NOT NULL AND ISNULL(c.IsDeleted,0)=0;
CREATE UNIQUE CLUSTERED INDEX IX_LegacySources ON #LegacyCaseDateSources(ShaleClientId,CaseId,SystemKey);
SELECT DISTINCT ShaleClientId INTO #ParticipatingTenants FROM #LegacyCaseDateSources;
SELECT pt.ShaleClientId EffectiveTenantId,e.SystemKey,e.Name ExpectedName,e.CalendarCategory ExpectedCategory,e.SupportsTime ExpectedSupportsTime,
 tc.NonDeletedTenantCount,tc.DeletedTenantCount,gc.GlobalCount,
 COALESCE(tw.Id,gw.Id) EffectiveCaseDateTypeId,COALESCE(tw.ShaleClientId,gw.ShaleClientId) TypeOwnerTenantId,COALESCE(tw.Name,gw.Name) ActualName,COALESCE(tw.CalendarCategory,gw.CalendarCategory) ActualCategory,COALESCE(tw.SupportsTime,gw.SupportsTime) ActualSupportsTime,COALESCE(tw.IsActive,gw.IsActive) IsActive,COALESCE(tw.IsDeleted,gw.IsDeleted) IsDeleted,
 CASE WHEN tw.Id IS NOT NULL THEN 'TENANT_OVERRIDE' WHEN gw.Id IS NOT NULL THEN 'GLOBAL_OR_RESET_FALLBACK' ELSE 'MISSING' END ResolutionSource
INTO #EffectiveCaseDateTypes FROM #ParticipatingTenants pt CROSS JOIN #ExpectedTypes e
OUTER APPLY(SELECT SUM(CASE WHEN ISNULL(IsDeleted,0)=0 THEN 1 ELSE 0 END) NonDeletedTenantCount,SUM(CASE WHEN ISNULL(IsDeleted,0)=1 THEN 1 ELSE 0 END) DeletedTenantCount FROM dbo.CaseDateTypes WHERE ShaleClientId=pt.ShaleClientId AND SystemKey=e.SystemKey) tc
OUTER APPLY(SELECT COUNT_BIG(*) GlobalCount FROM dbo.CaseDateTypes WHERE ShaleClientId IS NULL AND SystemKey=e.SystemKey) gc
OUTER APPLY(SELECT TOP(1) * FROM dbo.CaseDateTypes WHERE ShaleClientId=pt.ShaleClientId AND SystemKey=e.SystemKey AND ISNULL(IsDeleted,0)=0 ORDER BY Id) tw
OUTER APPLY(SELECT TOP(1) * FROM dbo.CaseDateTypes WHERE ShaleClientId IS NULL AND SystemKey=e.SystemKey ORDER BY Id) gw;
CREATE UNIQUE CLUSTERED INDEX IX_EffectiveTypes ON #EffectiveCaseDateTypes(EffectiveTenantId,SystemKey);
SELECT l.*,et.EffectiveCaseDateTypeId,et.ResolutionSource,
 SUM(CASE WHEN cd.Id IS NOT NULL AND cd.StartsAt=l.ExpectedStartsAt AND cd.EndsAt IS NULL AND cd.AllDay=l.ExpectedAllDay AND ISNULL(cd.IsDeleted,0)=0 THEN 1 ELSE 0 END) ActiveExactMatches,
 SUM(CASE WHEN cd.Id IS NOT NULL AND NOT(cd.StartsAt=l.ExpectedStartsAt AND cd.EndsAt IS NULL AND cd.AllDay=l.ExpectedAllDay) AND ISNULL(cd.IsDeleted,0)=0 THEN 1 ELSE 0 END) ActiveSameKeyDifferentValue,
 SUM(CASE WHEN cd.Id IS NOT NULL AND cd.StartsAt=l.ExpectedStartsAt AND cd.EndsAt IS NULL AND cd.AllDay=l.ExpectedAllDay AND ISNULL(cd.IsDeleted,0)=1 THEN 1 ELSE 0 END) RemovedExactMatches
INTO #OccurrenceEvidence FROM #LegacyCaseDateSources l
LEFT JOIN #EffectiveCaseDateTypes et ON et.EffectiveTenantId=l.ShaleClientId AND et.SystemKey=l.SystemKey
LEFT JOIN dbo.CaseDateTypes variants ON variants.SystemKey=l.SystemKey AND (variants.ShaleClientId=l.ShaleClientId OR variants.ShaleClientId IS NULL)
LEFT JOIN dbo.CaseDates cd ON cd.ShaleClientId=l.ShaleClientId AND cd.CaseId=l.CaseId AND cd.CaseDateTypeId=variants.Id
GROUP BY l.ShaleClientId,l.CaseId,l.FieldName,l.SystemKey,l.ExpectedStartsAt,l.ExpectedAllDay,et.EffectiveCaseDateTypeId,et.ResolutionSource;
SELECT '00_DRAFT_SYSTEMKEY_COLLISION' SectionName,@DraftAliasDefinitionCount DraftAliasDefinitionCount,@DraftAliasOccurrenceCount DraftAliasOccurrenceCount;
SELECT '01_GLOBAL_SEED_COMPATIBILITY' SectionName,*,CASE WHEN GlobalDefinitionCount=0 THEN 'EXPECTED_MISSING_SEED_CAN_CREATE' WHEN GlobalDefinitionCount>1 OR ExactNameConflictCount>0 OR CategoryConflictCount>0 OR SupportsTimeConflictCount>0 OR InactiveCount>0 OR DeletedCount>0 THEN 'BLOCKS_SEED' ELSE 'SEED_COMPATIBLE' END Classification FROM #GlobalSeedProfile ORDER BY SystemKey;
SELECT '02_PARTICIPATING_TENANTS' SectionName,ShaleClientId,COUNT_BIG(*) EligibleSourceRows FROM #LegacyCaseDateSources GROUP BY ShaleClientId ORDER BY ShaleClientId;
SELECT '03_ELIGIBLE_COUNTS_BY_FIELD' SectionName,ShaleClientId,FieldName,COUNT_BIG(*) EligibleRows FROM #LegacyCaseDateSources GROUP BY ShaleClientId,FieldName ORDER BY ShaleClientId,FieldName;
SELECT '04_EFFECTIVE_TYPE_MATRIX' SectionName,* FROM #EffectiveCaseDateTypes ORDER BY EffectiveTenantId,SystemKey;
SELECT '05_EFFECTIVE_TYPE_BLOCKERS' SectionName,* FROM #EffectiveCaseDateTypes WHERE EffectiveCaseDateTypeId IS NULL OR ISNULL(NonDeletedTenantCount,0)>1 OR GlobalCount<>1 OR ISNULL(IsActive,0)<>1 OR ISNULL(IsDeleted,0)<>0 OR ActualCategory<>ExpectedCategory OR ActualSupportsTime<>ExpectedSupportsTime;
SELECT '06_ORPHAN_CALLER_TIME' SectionName,ShaleClientId,Id AS CaseId FROM dbo.Cases WHERE CallerTime IS NOT NULL AND CallerDate IS NULL ORDER BY ShaleClientId,Id;
SELECT '07_INTAKE_TIMED_ALL_DAY_COUNTS' SectionName,ShaleClientId,SUM(CASE WHEN ExpectedAllDay=0 THEN 1 ELSE 0 END) TimedRows,SUM(CASE WHEN ExpectedAllDay=1 THEN 1 ELSE 0 END) AllDayRows FROM #LegacyCaseDateSources WHERE SystemKey='intake' GROUP BY ShaleClientId;
SELECT '08_SAME_SYSTEMKEY_OCCURRENCE_EVIDENCE' SectionName,ShaleClientId,SystemKey,COUNT_BIG(*) EligibleSourceRows,SUM(ActiveExactMatches) ActiveExactMatches,SUM(CASE WHEN ActiveExactMatches>1 THEN 1 ELSE 0 END) SourcesWithMultipleActiveExactMatches,SUM(CASE WHEN ActiveSameKeyDifferentValue>0 THEN 1 ELSE 0 END) SourcesWithActiveDifferentValues,SUM(CASE WHEN RemovedExactMatches>0 THEN 1 ELSE 0 END) SourcesWithRemovedExactMatches FROM #OccurrenceEvidence GROUP BY ShaleClientId,SystemKey ORDER BY ShaleClientId,SystemKey;
SELECT '09_OCCURRENCE_CONFLICT_SAFE_IDS' SectionName,ShaleClientId,CaseId,FieldName,SystemKey,ActiveExactMatches,ActiveSameKeyDifferentValue,RemovedExactMatches FROM #OccurrenceEvidence WHERE ActiveExactMatches>1 OR ActiveSameKeyDifferentValue>0 OR RemovedExactMatches>0;
SELECT '10_CROSS_TENANT_CASE_TYPE' SectionName,cd.ShaleClientId CaseDateTenantId,c.ShaleClientId CaseTenantId,t.ShaleClientId TypeOwnerTenantId,COUNT_BIG(*) Rows FROM dbo.CaseDates cd LEFT JOIN dbo.Cases c ON c.Id=cd.CaseId LEFT JOIN dbo.CaseDateTypes t ON t.Id=cd.CaseDateTypeId WHERE c.Id IS NULL OR t.Id IS NULL OR c.ShaleClientId<>cd.ShaleClientId OR (t.ShaleClientId IS NOT NULL AND t.ShaleClientId<>cd.ShaleClientId) GROUP BY cd.ShaleClientId,c.ShaleClientId,t.ShaleClientId;
SELECT '11_CREATED_BY_TENANT_MISMATCH' SectionName,cd.ShaleClientId CaseDateTenantId,cd.CreatedByUserId,COUNT_BIG(*) Rows FROM dbo.CaseDates cd LEFT JOIN dbo.Users u ON u.Id=cd.CreatedByUserId AND u.ShaleClientId=cd.ShaleClientId WHERE u.Id IS NULL GROUP BY cd.ShaleClientId,cd.CreatedByUserId;
SELECT '12_WORKFLOW_FLAG_DATE_ANOMALIES' SectionName,v.AnomalyClass,COUNT_BIG(*) AnomalyCount FROM dbo.Cases c CROSS APPLY(VALUES (CASE WHEN ISNULL(c.FeeAgreementSigned,0)=1 AND c.DateFeeAgreementSigned IS NULL THEN 'FLAG_SET_DATE_MISSING' WHEN ISNULL(c.FeeAgreementSigned,0)=0 AND c.DateFeeAgreementSigned IS NOT NULL THEN 'DATE_PRESENT_FLAG_NOT_SET' END),(CASE WHEN ISNULL(c.NonEngagementLetterSent,0)=1 AND c.DateNonEngagementLetterSent IS NULL THEN 'FLAG_SET_DATE_MISSING' WHEN ISNULL(c.NonEngagementLetterSent,0)=0 AND c.DateNonEngagementLetterSent IS NOT NULL THEN 'DATE_PRESENT_FLAG_NOT_SET' END))v(AnomalyClass) WHERE v.AnomalyClass IS NOT NULL GROUP BY v.AnomalyClass;
IF OBJECT_ID(N'dbo.CaseStatuses',N'U') IS NOT NULL BEGIN
 SELECT '13_STATUS_HISTORY_EVIDENCE' SectionName,v.FieldName,c.ShaleClientId,COUNT_BIG(*) LegacyRows,SUM(CASE WHEN h.MatchCount=0 THEN 1 ELSE 0 END) MissingEvidence,SUM(CASE WHEN h.MatchCount>1 THEN 1 ELSE 0 END) RepeatedEvidence FROM dbo.Cases c CROSS APPLY(VALUES('AcceptedDate','accepted',c.AcceptedDate),('DeniedDate','denied',c.DeniedDate),('ClosedDate','closed',c.ClosedDate))v(FieldName,LifecycleKey,LegacyDate) CROSS APPLY(SELECT COUNT_BIG(*) MatchCount FROM dbo.CaseStatuses cs JOIN dbo.Statuses s ON s.Id=cs.StatusId AND (s.ShaleClientId=c.ShaleClientId OR s.ShaleClientId IS NULL) WHERE cs.CaseId=c.Id AND CAST(cs.EffectiveDate AS date)=v.LegacyDate AND (s.LifecycleKey=v.LifecycleKey OR s.SystemKey=v.LifecycleKey))h WHERE v.LegacyDate IS NOT NULL GROUP BY v.FieldName,c.ShaleClientId;
 SELECT '14_REOPENED_OR_REPEATED_TRANSITIONS' SectionName,c.ShaleClientId,c.Id CaseId,COUNT_BIG(*) RelevantRows FROM dbo.Cases c JOIN dbo.CaseStatuses cs ON cs.CaseId=c.Id JOIN dbo.Statuses s ON s.Id=cs.StatusId AND (s.ShaleClientId=c.ShaleClientId OR s.ShaleClientId IS NULL) WHERE s.LifecycleKey IN('accepted','denied','closed') OR s.SystemKey IN('accepted','denied','closed','reopened') GROUP BY c.ShaleClientId,c.Id HAVING COUNT_BIG(*)>1;
END;
SELECT '15_REQUIRED_MIGRATION_ACTORS' SectionName,ShaleClientId FROM #ParticipatingTenants ORDER BY ShaleClientId;
DECLARE @SeedBlockers bigint=(SELECT COUNT_BIG(*) FROM #GlobalSeedProfile WHERE GlobalDefinitionCount>1 OR ExactNameConflictCount>0 OR CategoryConflictCount>0 OR SupportsTimeConflictCount>0 OR InactiveCount>0 OR DeletedCount>0);
SET @SeedBlockers=@SeedBlockers+@DraftAliasDefinitionCount+@DraftAliasOccurrenceCount;
DECLARE @MissingSeedable bigint=(SELECT COUNT_BIG(*) FROM #GlobalSeedProfile WHERE GlobalDefinitionCount=0);
DECLARE @ParticipatingTenantCount bigint=(SELECT COUNT_BIG(*) FROM #ParticipatingTenants);
DECLARE @EligibleSourceRowCount bigint=(SELECT COUNT_BIG(*) FROM #LegacyCaseDateSources);
DECLARE @VisibilityConfirmed bit=CONVERT(bit,CASE WHEN @OperatorVerifiedAllTenantVisibility=1 AND @SessionTenantId IS NULL AND @IsAdministrativePrincipal=1 AND @ParticipatingTenantCount>0 AND @EligibleSourceRowCount>0 THEN 1 ELSE 0 END);
DECLARE @Unresolved bigint=(SELECT COUNT_BIG(*) FROM #LegacyCaseDateSources l LEFT JOIN #EffectiveCaseDateTypes et ON et.EffectiveTenantId=l.ShaleClientId AND et.SystemKey=l.SystemKey WHERE et.EffectiveCaseDateTypeId IS NULL OR ISNULL(et.NonDeletedTenantCount,0)>1 OR et.GlobalCount<>1 OR ISNULL(et.IsActive,0)<>1 OR ISNULL(et.IsDeleted,0)<>0 OR et.ActualCategory<>et.ExpectedCategory OR et.ActualSupportsTime<>et.ExpectedSupportsTime);
DECLARE @Orphans bigint=(SELECT COUNT_BIG(*) FROM dbo.Cases WHERE CallerTime IS NOT NULL AND CallerDate IS NULL),@Conflicts bigint=(SELECT COUNT_BIG(*) FROM #OccurrenceEvidence WHERE ActiveExactMatches>1 OR ActiveSameKeyDifferentValue>0 OR RemovedExactMatches>0);
DECLARE @CrossTenant bigint=(SELECT COUNT_BIG(*) FROM dbo.CaseDates cd LEFT JOIN dbo.Cases c ON c.Id=cd.CaseId LEFT JOIN dbo.CaseDateTypes t ON t.Id=cd.CaseDateTypeId WHERE c.Id IS NULL OR t.Id IS NULL OR c.ShaleClientId<>cd.ShaleClientId OR (t.ShaleClientId IS NOT NULL AND t.ShaleClientId<>cd.ShaleClientId));
DECLARE @ActorMismatch bigint=(SELECT COUNT_BIG(*) FROM dbo.CaseDates cd LEFT JOIN dbo.Users u ON u.Id=cd.CreatedByUserId AND u.ShaleClientId=cd.ShaleClientId WHERE u.Id IS NULL);
DECLARE @FlagSetDateMissing bigint=(SELECT COUNT_BIG(*) FROM dbo.Cases c CROSS APPLY(VALUES (CASE WHEN ISNULL(c.FeeAgreementSigned,0)=1 AND c.DateFeeAgreementSigned IS NULL THEN 1 END),(CASE WHEN ISNULL(c.NonEngagementLetterSent,0)=1 AND c.DateNonEngagementLetterSent IS NULL THEN 1 END))v(IsAnomaly) WHERE v.IsAnomaly=1);
DECLARE @DatePresentFlagNotSet bigint=(SELECT COUNT_BIG(*) FROM dbo.Cases c CROSS APPLY(VALUES (CASE WHEN ISNULL(c.FeeAgreementSigned,0)=0 AND c.DateFeeAgreementSigned IS NOT NULL THEN 1 END),(CASE WHEN ISNULL(c.NonEngagementLetterSent,0)=0 AND c.DateNonEngagementLetterSent IS NOT NULL THEN 1 END))v(IsAnomaly) WHERE v.IsAnomaly=1);
DECLARE @BackfillBlockerCount bigint=(CASE WHEN @VisibilityConfirmed=1 THEN 0 ELSE 1 END)+@MissingSeedable+@SeedBlockers+@Unresolved+@Orphans+@Conflicts+@CrossTenant+@ActorMismatch;
SELECT 'PREFLIGHT_VALIDATION_SUMMARY' SectionName,CONVERT(nvarchar(128),@SessionTenantId) SessionContextShaleClientId,@ParticipatingTenantCount ParticipatingTenantCount,@EligibleSourceRowCount EligibleSourceRowCount,CASE WHEN @VisibilityConfirmed=1 THEN 'OPERATOR_VERIFIED_ALL_TENANT_VISIBILITY' ELSE 'OPERATOR_VERIFICATION_REQUIRED' END VisibilityReadiness,@DraftAliasDefinitionCount DraftAliasDefinitionCount,@DraftAliasOccurrenceCount DraftAliasOccurrenceCount,@MissingSeedable ExpectedMissingTypesSeedMayCreate,@SeedBlockers SeedBlockerCount,@Unresolved UnresolvedSourceCount,@Orphans OrphanCallerTimeCount,@Conflicts OccurrenceConflictCount,@CrossTenant CrossTenantOrBrokenRelationshipCount,@ActorMismatch CreatedByTenantMismatchCount,@FlagSetDateMissing FlagSetDateMissingCount,@DatePresentFlagNotSet DatePresentFlagNotSetCount,@BackfillBlockerCount BackfillBlockerCount,CASE WHEN @VisibilityConfirmed=1 AND @SeedBlockers=0 AND @DraftAliasDefinitionCount=0 AND @DraftAliasOccurrenceCount=0 THEN 'READY_FOR_SEED_REVIEW' ELSE 'BLOCKED_FOR_SEED' END SeedReadiness,CASE WHEN @BackfillBlockerCount=0 THEN 'READY_FOR_BACKFILL_REVIEW' ELSE 'BLOCKED_FOR_BACKFILL' END BackfillReadiness;
