-- Permit durable case delete/restore entity-action audit events.
ALTER TABLE dbo.EntityActionAuditLog DROP CONSTRAINT CK_EntityActionAuditLog_EntityType;
ALTER TABLE dbo.EntityActionAuditLog ADD CONSTRAINT CK_EntityActionAuditLog_EntityType
    CHECK (EntityType IN ('CASE','LINK_TYPE','CASE_LINK','CASE_LINK_SHARE','MATERIAL_TYPE','MATERIAL_REQUEST','MATERIAL_REQUEST_FOLLOW_UP','MATERIAL_ITEM','CASE_DATE','FORM_CONFIGURATION','USER'));

ALTER TABLE dbo.EntityActionAuditLog DROP CONSTRAINT CK_EntityActionAuditLog_Action;
ALTER TABLE dbo.EntityActionAuditLog ADD CONSTRAINT CK_EntityActionAuditLog_Action
    CHECK (Action IN ('CREATED','OVERRIDE_CREATED','UPDATED','ACTIVATED','DEACTIVATED','OVERRIDE_RESET','DELETED','RESTORED','PRIMARY_SET','REORDERED','ADDED','REMOVED','STATUS_CHANGED','FOLLOW_UP_ADDED','LINKED','UNLINKED','LOCATION_UPDATED','RELEASED'));
