SET XACT_ABORT ON;
BEGIN TRY
BEGIN TRANSACTION;
IF OBJECT_ID(N'dbo.CaseDateTypeSemanticRoleMappings',N'U') IS NULL THROW 56810, 'Missing Case Date semantic-role foundation.', 1;
IF OBJECT_ID(N'dbo.EntityActionAuditLog',N'U') IS NULL THROW 56811, 'Missing entity-action audit foundation.', 1;
IF OBJECT_ID(N'dbo.CK_EntityActionAuditLog_EntityType',N'C') IS NOT NULL
 ALTER TABLE dbo.EntityActionAuditLog DROP CONSTRAINT CK_EntityActionAuditLog_EntityType;
ALTER TABLE dbo.EntityActionAuditLog ADD CONSTRAINT CK_EntityActionAuditLog_EntityType CHECK
 (EntityType IN ('CASE','LINK_TYPE','CASE_LINK','CASE_LINK_SHARE','MATERIAL_TYPE','MATERIAL_REQUEST','MATERIAL_REQUEST_FOLLOW_UP','MATERIAL_ITEM','CASE_DATE','CASE_DATE_ROLE_MAPPING','FORM_CONFIGURATION','USER'));
COMMIT TRANSACTION;
END TRY
BEGIN CATCH
 IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
 THROW;
END CATCH;
