SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;
    IF OBJECT_ID(N'dbo.EntityActionAuditLog',N'U') IS NULL
    BEGIN
        THROW 57054, 'EntityActionAuditLog does not exist.', 1;
    END;
    IF EXISTS (SELECT 1 FROM dbo.EntityActionAuditLog WHERE EntityType='TASK_POLICY_CONFIGURATION')
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.EntityActionAuditLog') AND definition LIKE '%TASK_POLICY_CONFIGURATION%')
    BEGIN
        THROW 57055, 'Task policy audit rows exist outside the current allowlist.', 1;
    END;
    IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.EntityActionAuditLog') AND name=N'CK_EntityActionAuditLog_EntityType')
        ALTER TABLE dbo.EntityActionAuditLog DROP CONSTRAINT CK_EntityActionAuditLog_EntityType;
    ALTER TABLE dbo.EntityActionAuditLog WITH CHECK ADD CONSTRAINT CK_EntityActionAuditLog_EntityType CHECK (EntityType IN
    ('CONTACT','CONTACT_PHONE_NUMBER','CONTACT_EMAIL_ADDRESS','CONTACT_ADDRESS','ORGANIZATION','ORGANIZATION_PHONE','ORGANIZATION_EMAIL','ORGANIZATION_ADDRESS','ORGANIZATION_WEBSITE','CASE','CASE_OVERVIEW_CONFIGURATION','CASE_DATE_PRESENTATION_CONFIGURATION','CASE_STATUS','LINK_TYPE','CASE_LINK','CASE_LINK_SHARE','CASE_DATE','CASE_DATE_TYPE','CASE_TEAM_ROLE','CASE_TEAM_MEMBER','CASE_TEAM_MEMBER_ROLE','FIRM_WIDE_ROLE','USER_FIRM_WIDE_ROLE','FIELD_CONFIRMATION_POLICY','SAVED_VALUE_CONFIRMATION','CALENDAR_EVENT','CASE_DATE_ROLE_MAPPING','FORM_CONFIGURATION','MATERIAL_TYPE','MATERIAL_REQUEST','MATERIAL_REQUEST_FOLLOW_UP','MATERIAL_ITEM','USER','CONTACT_TYPE','SPECIALTY','CREDENTIAL_DEFINITION','CONTACT_CONTACT_TYPE','CONTACT_SPECIALTY','CONTACT_CREDENTIAL','ORGANIZATION_TYPE','ORGANIZATION_ORGANIZATION_TYPE','TASK_POLICY_CONFIGURATION'));
    ALTER TABLE dbo.EntityActionAuditLog CHECK CONSTRAINT CK_EntityActionAuditLog_EntityType;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
