package com.shale.desktop.session;

import static org.junit.jupiter.api.Assertions.*;import java.time.Instant;import java.util.UUID;import java.util.concurrent.CountDownLatch;import org.junit.jupiter.api.Test;

class DesktopSessionEnrollmentLifecycleTest {
 @Test void successInstallsMemoryOnlyCredentialAndLogoutRevokesThenClears(){var client=new Client();var holder=new DesktopServerSession();var lifecycle=new DesktopSessionEnrollmentLifecycle(client,holder);lifecycle.stage(7,9,"u@test","password");lifecycle.enroll(44L);assertEquals(DesktopSessionEnrollmentLifecycle.State.ENROLLED,lifecycle.state());assertTrue(holder.current().isPresent());assertEquals(44L,client.instance);lifecycle.logout();assertTrue(holder.current().isEmpty());assertEquals(1,client.logouts);}
 @Test void unavailableEndpointDowngradesButSecurityAndMalformedResponsesFailClosed(){for(var failure:new DesktopSessionEnrollmentClient.Failure[]{DesktopSessionEnrollmentClient.Failure.ENDPOINT_UNAVAILABLE,DesktopSessionEnrollmentClient.Failure.TRANSIENT,DesktopSessionEnrollmentClient.Failure.SECURITY_REJECTED,DesktopSessionEnrollmentClient.Failure.MALFORMED_RESPONSE}){var client=new Client();client.failure=failure;var lifecycle=new DesktopSessionEnrollmentLifecycle(client,new DesktopServerSession());lifecycle.stage(7,9,"u@test","password");lifecycle.enroll(null);assertEquals(failure==DesktopSessionEnrollmentClient.Failure.ENDPOINT_UNAVAILABLE||failure==DesktopSessionEnrollmentClient.Failure.TRANSIENT?DesktopSessionEnrollmentLifecycle.State.COMPATIBILITY:DesktopSessionEnrollmentLifecycle.State.SECURITY_REJECTED,lifecycle.state());assertTrue(lifecycle.session().current().isEmpty());}}
 @Test void newGenerationAndShutdownClearPreviousBearer(){var client=new Client();var lifecycle=new DesktopSessionEnrollmentLifecycle(client,new DesktopServerSession());lifecycle.stage(7,9,"a@test","a");lifecycle.enroll(null);lifecycle.stage(7,10,"b@test","b");assertTrue(lifecycle.session().current().isEmpty(),"user switch must clear the prior bearer before exchange");lifecycle.shutdown();assertTrue(lifecycle.session().current().isEmpty());assertEquals(0,client.logouts,"process exit is not logical logout");}
 @Test void staleBackgroundCompletionCannotInstallPreviousUsersBearer()throws Exception{var entered=new CountDownLatch(1);var release=new CountDownLatch(1);var client=new Client(){@Override public DesktopServerSession.Credential enroll(String e,String p,Long i)throws EnrollmentException{entered.countDown();try{release.await();}catch(InterruptedException interrupted){Thread.currentThread().interrupt();throw new EnrollmentException(Failure.TRANSIENT,interrupted);}return super.enroll(e,p,i);}};var lifecycle=new DesktopSessionEnrollmentLifecycle(client,new DesktopServerSession());lifecycle.stage(7,9,"a@test","a");var worker=new Thread(()->lifecycle.enroll(44L));worker.start();entered.await();lifecycle.stage(7,10,"b@test","b");release.countDown();worker.join();assertTrue(lifecycle.session().current().isEmpty(),"a stale enrollment completion must not install the previous user's bearer");assertEquals(DesktopSessionEnrollmentLifecycle.State.PENDING,lifecycle.state());}
 static class Client extends DesktopSessionEnrollmentClient{Failure failure;Long instance;int logouts;Client(){super("https://example.test");}@Override public DesktopServerSession.Credential enroll(String e,String p,Long i)throws EnrollmentException{instance=i;if(failure!=null)throw new EnrollmentException(failure);return new DesktopServerSession.Credential("header.payload.signature",UUID.randomUUID(),UUID.randomUUID(),Instant.now().plusSeconds(60));}@Override public void logout(String token){logouts++;}}
}
