package com.shale.ui.controller;

import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.Executor;
import java.util.concurrent.atomic.AtomicLong;
import com.shale.core.service.UserServicePort;
import com.shale.ui.component.dialog.AppDialogs;
import com.shale.ui.services.UiRuntimeBridge;
import com.shale.ui.state.AppState;
import com.shale.ui.util.*;
import javafx.application.Platform;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.layout.*;

/** Tenant-administrator Phase 10 session surface; all session reads and mutations use the audited server API. */
public final class AdminSessionsPane extends VBox {
    static final int PAGE_SIZE=50;
    private static final DateTimeFormatter TIME=DateTimeFormatter.ofPattern("MMM d, yyyy 'at' h:mm a");
    private final UiRuntimeBridge runtime;private final AppState state;private final UserServicePort users;private final Executor executor;
    private final AtomicLong generation=new AtomicLong();private final VBox rows=new VBox(8);private final Label message=new Label(),pageLabel=new Label();
    private final ComboBox<UserOption> userFilter=new ComboBox<>();private final ComboBox<String> clientFilter=new ComboBox<>();private final ComboBox<WindowOption> sinceFilter=new ComboBox<>();private final CheckBox activeOnly=new CheckBox("Active only");
    private final Button refresh,clear,previous,next;private boolean open,loading,suppressFilterEvents;private int page;
    public AdminSessionsPane(UiRuntimeBridge runtime,AppState state,UserServicePort users,Executor executor){super(10);this.runtime=runtime;this.state=state;this.users=users;this.executor=executor;getStyleClass().add("devices-sessions-pane");
        userFilter.setPromptText("All users");clientFilter.getItems().setAll("All clients","Desktop","Web","Mobile");clientFilter.getSelectionModel().selectFirst();sinceFilter.getItems().setAll(WindowOption.values());sinceFilter.getSelectionModel().selectFirst();
        ControlStyles.formControl(userFilter);ControlStyles.formControl(clientFilter);ControlStyles.formControl(sinceFilter);
        refresh=ActionButtonFactory.semantic("Refresh",e->load(),ControlStyles.Purpose.SECONDARY,ControlStyles.Size.SMALL);clear=ActionButtonFactory.semantic("Clear filters",e->resetFilters(),ControlStyles.Purpose.GHOST,ControlStyles.Size.SMALL);previous=ActionButtonFactory.semantic("Previous",e->{if(page>0){page--;load();}},ControlStyles.Purpose.SECONDARY,ControlStyles.Size.SMALL);next=ActionButtonFactory.semantic("Next",e->{page++;load();},ControlStyles.Purpose.SECONDARY,ControlStyles.Size.SMALL);
        FlowPane filters=new FlowPane(8,8,new Label("User"),userFilter,new Label("Client"),clientFilter,activeOnly,new Label("Since"),sinceFilter,clear,refresh);HBox paging=new HBox(8,previous,pageLabel,next);paging.setAlignment(Pos.CENTER_LEFT);message.setWrapText(true);message.getStyleClass().add("settings-state-message");getChildren().addAll(filters,message,rows,paging);
        userFilter.valueProperty().addListener((o,a,b)->filterChanged());clientFilter.valueProperty().addListener((o,a,b)->filterChanged());sinceFilter.valueProperty().addListener((o,a,b)->filterChanged());activeOnly.selectedProperty().addListener((o,a,b)->filterChanged());sceneProperty().addListener((o,oldScene,newScene)->{if(oldScene!=null&&newScene==null)dispose();});}
    public void open(){if(open)return;open=true;loadUsers();load();}
    public void dispose(){open=false;loading=false;generation.incrementAndGet();rows.getChildren().clear();userFilter.getItems().clear();message.setText("");}
    public boolean mutationInFlight(){return loading;}
    private void loadUsers(){Identity who=identity();long token=generation.get();executor.execute(()->{try{List<UserOption> options=users.listTenantUsers(who.tenant()).stream().map(u->new UserOption(u.id(),u.displayName(),u.email())).toList();Platform.runLater(()->{if(!stale(token,who))userFilter.getItems().setAll(options);});}catch(RuntimeException ignored){/* Session listing remains usable without the optional selector directory. */}});}
    void load(){if(!open||loading)return;loading=true;long token=generation.incrementAndGet();Identity who=identity();UiRuntimeBridge.AdminSessionFilter filter=filter();busy("Loading tenant sessions…");Optional<UiRuntimeBridge.AdminSessionManagement> service=runtime==null?Optional.empty():runtime.adminSessionManagement();if(service.isEmpty()){loading=false;busy("Administrative session management is unavailable for this connection.");return;}executor.execute(()->{try{var loaded=service.get().list(filter);Platform.runLater(()->apply(token,who,loaded));}catch(RuntimeException failure){Platform.runLater(()->fail(token,who,failure));}});}
    private void apply(long token,Identity who,UiRuntimeBridge.AdminSessionPage loaded){if(stale(token,who))return;loading=false;rows.getChildren().clear();loaded.items().forEach(s->rows.getChildren().add(card(s)));message.setText(loaded.items().isEmpty()?"No sessions match these filters.":"");pageLabel.setText("Page "+(page+1));previous.setDisable(page==0);next.setDisable(loaded.items().size()<PAGE_SIZE);setInputsDisabled(false);}
    private VBox card(UiRuntimeBridge.AdminSessionView s){Instant now=Instant.now();boolean expired=!now.isBefore(s.expiresAt()),revoked=s.revokedAt()!=null;String status=revoked?"Revoked":expired?"Expired":"Active";String owner=blank(s.userDisplayName())?blank(s.userEmail())?"User":s.userEmail():s.userDisplayName();Label title=new Label(owner);title.getStyleClass().add("settings-management-title");Label identity=new Label(blank(s.userEmail())?"":s.userEmail());identity.getStyleClass().add("search-summary-text");Label badge=new Label(status+(s.currentSession()?" · Current administrator session":""));badge.getStyleClass().addAll("shale-status-pill",revoked||expired?"session-status-inactive":"session-status-current");VBox facts=new VBox(3,line("Client",DevicesSessionsPane.client(s.clientType())),line("Signed in",time(s.issuedAt())),line("Last refreshed",time(s.lastRefreshedAt())),line("Expires",time(s.expiresAt())));if(revoked){facts.getChildren().add(line("Revoked",time(s.revokedAt())));facts.getChildren().add(line("Reason",reason(s.revocationReason())));}VBox card=new VBox(7,new HBox(8,title,badge),identity,facts);card.getStyleClass().addAll("shale-card","session-card");if(!revoked&&!expired&&!s.currentSession())card.getChildren().add(ActionButtonFactory.semantic("Revoke session",e->confirm(s,owner),ControlStyles.Purpose.DANGER,ControlStyles.Size.SMALL));else if(s.currentSession())card.getChildren().add(line("Protection","Use ordinary logout to end this session."));return card;}
    private void confirm(UiRuntimeBridge.AdminSessionView s,String owner){String context=owner+" · "+DevicesSessionsPane.client(s.clientType())+" · signed in "+time(s.issuedAt());String copy="Revoke "+context+"? Server access will be revoked. The remote application may not close instantly; its next authoritative validation will reject the session, and an existing live notification may accelerate that check.";if(AppDialogs.showDestructiveConfirmation(getScene()==null?null:getScene().getWindow(),"Revoke session?","Revoke this tenant session?",copy,"Revoke session"))revoke(s);}
    private void revoke(UiRuntimeBridge.AdminSessionView target){if(target.currentSession()||loading)return;loading=true;long token=generation.incrementAndGet();Identity who=identity();busy("Revoking session…");executor.execute(()->{try{runtime.adminSessionManagement().orElseThrow().revoke(target.sessionId());Platform.runLater(()->{if(!stale(token,who)){loading=false;load();}});}catch(RuntimeException failure){Platform.runLater(()->fail(token,who,failure));}});}
    private void fail(long token,Identity who,RuntimeException failure){if(stale(token,who))return;loading=false;setInputsDisabled(false);String text=failure.getMessage()!=null&&failure.getMessage().contains("Administrator access")?"Administrator authorization is unavailable.":"Sessions could not be loaded or changed. Existing results remain visible; check your connection and try again.";message.setText(text);}
    private void filterChanged(){if(!open||suppressFilterEvents)return;page=0;generation.incrementAndGet();loading=false;load();}
    private void resetFilters(){suppressFilterEvents=true;try{userFilter.getSelectionModel().clearSelection();clientFilter.getSelectionModel().selectFirst();activeOnly.setSelected(false);sinceFilter.getSelectionModel().selectFirst();}finally{suppressFilterEvents=false;}filterChanged();}
    private UiRuntimeBridge.AdminSessionFilter filter(){UserOption user=userFilter.getValue();String c=clientFilter.getValue();WindowOption w=sinceFilter.getValue();return new UiRuntimeBridge.AdminSessionFilter(user==null?null:user.id(),c==null||c.startsWith("All")?null:c.toUpperCase(Locale.ROOT),activeOnly.isSelected(),w==null?null:w.since(),page,PAGE_SIZE);}
    private void busy(String text){message.setText(text);setInputsDisabled(true);}private void setInputsDisabled(boolean disabled){refresh.setDisable(disabled);clear.setDisable(disabled);previous.setDisable(disabled||page==0);next.setDisable(disabled);userFilter.setDisable(disabled);clientFilter.setDisable(disabled);sinceFilter.setDisable(disabled);activeOnly.setDisable(disabled);}
    private boolean stale(long token,Identity who){return !open||token!=generation.get()||!who.equals(identity())||!state.isAdmin();}private Identity identity(){return new Identity(state==null?null:state.getShaleClientId(),state==null?null:state.getUserId());}
    private static Label line(String label,String value){Label l=new Label(label+": "+value);l.setWrapText(true);l.getStyleClass().add("search-summary-text");return l;}private static String time(Instant value){return value==null?"Not available":TIME.format(value.atZone(ZoneId.systemDefault()));}private static boolean blank(String v){return v==null||v.isBlank();}
    static String reason(String value){if(value==null)return "Not available";return switch(value){case "ADMIN_REVOKED"->"Revoked by an administrator";case "USER_REVOKED"->"Revoked by the user";case "USER_LOGOUT"->"User logout";case "SECURITY"->"Account security change";default->"Session ended";};}
    record Identity(Integer tenant,Integer user){}record UserOption(int id,String name,String email){@Override public String toString(){return blank(name)?email:name+(blank(email)?"":" ("+email+")");}}
    enum WindowOption{ALL("Any time",null),DAYS_7("Last 7 days",Duration.ofDays(7)),DAYS_30("Last 30 days",Duration.ofDays(30)),DAYS_90("Last 90 days",Duration.ofDays(90));private final String label;private final Duration duration;WindowOption(String l,Duration d){label=l;duration=d;}Instant since(){return duration==null?null:Instant.now().minus(duration);}@Override public String toString(){return label;}}
}
