package com.shale.ui.controller;

import com.shale.core.dto.*;
import com.shale.core.service.MaterialItemServicePort;
import com.shale.core.service.MaterialRequestServicePort;
import com.shale.ui.component.dialog.AppDialogs;
import com.shale.ui.state.AppState;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Window;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;

/** Desktop Case View Materials tab coordinator. Service ports own tenant, PHI-read audit, RowVer, lifecycle, and relationship validation. */
final class CaseMaterialsTabController {
    private static final DateTimeFormatter DATE_TIME = DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a");
    private final ExecutorService executor = Executors.newFixedThreadPool(2, r -> { Thread t = new Thread(r, "case-materials-worker"); t.setDaemon(true); return t; });
    private final AtomicInteger requestGeneration = new AtomicInteger();
    private final AtomicInteger itemGeneration = new AtomicInteger();
    private final AtomicBoolean mutationInFlight = new AtomicBoolean();
    private MaterialRequestServicePort requestService; private MaterialItemServicePort itemService; private AppState appState; private Supplier<Long> caseIdSupplier; private Supplier<Window> ownerSupplier;
    private VBox root, requestList, itemList; private Label requestStatus, itemStatus, requestTitle, itemTitle; private Button addRequest, addItem;
    private List<MaterialRequestSummaryDto> requests = List.of(); private List<MaterialItemSummaryDto> items = List.of(); private boolean loaded;

    void init(MaterialRequestServicePort requestService, MaterialItemServicePort itemService, AppState appState, Supplier<Long> caseIdSupplier, Supplier<Window> ownerSupplier) {
        this.requestService = requestService; this.itemService = itemService; this.appState = appState; this.caseIdSupplier = caseIdSupplier; this.ownerSupplier = ownerSupplier;
    }
    Node view() {
        if (root != null) return root;
        requestList = new VBox(10); itemList = new VBox(10); requestStatus = muted("Loading material requests…"); itemStatus = muted("Loading received materials…"); requestTitle = title("Material Requests"); itemTitle = title("Received Materials");
        addRequest = primary("New Request"); addItem = primary("New Material"); addRequest.setOnAction(e -> openRequestEditor(null)); addItem.setOnAction(e -> openItemEditor(null));
        VBox requestsCard = section(requestTitle, addRequest, requestStatus, requestList); VBox itemsCard = section(itemTitle, addItem, itemStatus, itemList);
        HBox split = new HBox(12, requestsCard, itemsCard); split.setFillHeight(true); HBox.setHgrow(requestsCard, Priority.ALWAYS); HBox.setHgrow(itemsCard, Priority.ALWAYS);
        root = new VBox(10, split); root.setPadding(new Insets(8)); root.getStyleClass().add("case-main-surface"); return root;
    }
    void load() { if (!loaded) refreshAll(); }
    void refreshAll(){ refreshRequests(); refreshItems(); }
    void refreshRequests(){ long cid = caseId(); int tid = tenant(); int g = requestGeneration.incrementAndGet(); show(requestStatus,"Loading material requests…"); requestList.getChildren().clear(); run(() -> requestService.listMaterialRequests(cid, tid), list -> { if(staleRequest(g,cid))return; loaded=true; requests = orderRequests(list); renderRequests(); }, "Unable to load material requests."); }
    void refreshItems(){ long cid = caseId(); int tid = tenant(); int g = itemGeneration.incrementAndGet(); show(itemStatus,"Loading received materials…"); itemList.getChildren().clear(); run(() -> itemService.listMaterialItems(cid, tid), list -> { if(staleItem(g,cid))return; loaded=true; items = orderItems(list); renderItems(); }, "Unable to load received materials."); }
    private void renderRequests(){ requestTitle.setText("Material Requests ("+requests.size()+")"); requestList.getChildren().clear(); if(requests.isEmpty()) show(requestStatus,"No material requests yet."); else { hide(requestStatus); requests.forEach(r -> requestList.getChildren().add(requestCard(r))); } }
    private void renderItems(){ itemTitle.setText("Received Materials ("+items.size()+")"); itemList.getChildren().clear(); if(items.isEmpty()) show(itemStatus,"No received materials yet."); else { hide(itemStatus); items.forEach(i -> itemList.getChildren().add(itemCard(i))); } }
    private Node requestCard(MaterialRequestSummaryDto r){ VBox b=card(); b.getChildren().addAll(new HBox(8, typeDot(r.materialTypeSystemKey()), strong(nvl(r.title(), r.materialTypeName())), pill("Status: "+nvl(r.status(),"Unknown"))), line("From", source(r.requestedFromContactDisplayName(), r.requestedFromOrganizationName(), r.requestedFromText())), line("Assigned", nvl(r.assignedToDisplayName(),"Unassigned")), line("Requested / Due / Follow-up", fmt(r.requestedAt())+" • Due "+fmt(r.expectedResponseDate())+" • Next "+fmt(r.nextFollowUpAt()))); b.setOnMouseClicked(e->openRequestDetail(r.id())); return b; }
    private Node itemCard(MaterialItemSummaryDto i){ VBox b=card(); b.getChildren().addAll(new HBox(8, typeDot(i.materialTypeSystemKey()), strong(nvl(i.name(), i.materialTypeName())), pill("Custody: "+nvl(i.custodyStatus(),"Unknown"))), line("Format", nvl(i.format(),"Unknown")+" • "+nvl(i.completeness(),"Completeness unknown")), line("Received", fmt(i.receivedAt())+" by "+nvl(i.receivedByDisplayName(),"Unknown")), line("Counts", counts(i)+ (i.materialRequestId()!=null ? " • Linked to request" : " • No request link"))); b.setOnMouseClicked(e->openItemDetail(i.id())); return b; }
    private void openRequestDetail(long id){ long cid=caseId(); int tid=tenant(), actor=actor(); run(() -> requestService.getMaterialRequest(cid,id,tid,actor).orElseThrow(), d -> showRequestDetail(d), "Unable to open material request."); }
    private void showRequestDetail(MaterialRequestDetailDto d){ Dialog<Void> dlg=dialog("Material Request"); VBox c=new VBox(10, strong(nvl(d.title(),d.materialTypeName())), line("Status",nvl(d.status(),"Unknown")), line("Source",source(d.requestedFromContactDisplayName(),d.requestedFromOrganizationName(),d.requestedFromText())), line("Dates",fmt(d.requestedAt())+" • Follow-up "+fmt(d.nextFollowUpAt())), textBlock("Description", d.description()), textBlock("Notes", d.notes())); ButtonType follow=new ButtonType("Record Follow-up"); ButtonType edit=new ButtonType("Edit"); ButtonType status=new ButtonType("Change Status"); ButtonType del=new ButtonType("Delete", ButtonBar.ButtonData.LEFT); dlg.getDialogPane().getButtonTypes().addAll(follow,edit,status,del,ButtonType.CLOSE); dlg.getDialogPane().setContent(new ScrollPane(c)); button(dlg,follow,()->openFollowUp(d)); button(dlg,edit,()->openRequestEditor(d)); button(dlg,status,()->changeRequestStatus(d)); button(dlg,del,()->deleteRequest(d)); dlg.showAndWait(); }
    private void openFollowUp(MaterialRequestDetailDto d){ TextInputDialog t=new TextInputDialog(); t.setTitle("Record Follow-up"); t.setHeaderText("Append a follow-up note. Existing follow-ups cannot be edited or deleted."); t.showAndWait().ifPresent(note -> mutate(() -> requestService.recordFollowUp(new MaterialRequestServicePort.RecordMaterialRequestFollowUpCommand(tenant(),actor(),caseId(),d.id(), LocalDateTime.now(),actor(),"PHONE","NO_RESPONSE",d.nextFollowUpAt(),trim(note),d.rowVer())), this::refreshRequests, "Follow-up recorded.")); }
    private void openRequestEditor(MaterialRequestDetailDto existing){ TextInputDialog t=new TextInputDialog(existing==null?"":nvl(existing.title(),"")); t.setTitle(existing==null?"New Material Request":"Edit Material Request"); t.setHeaderText("Enter request title. Sensitive detail is saved only through the service."); t.showAndWait().ifPresent(title -> mutate(() -> { List<MaterialTypeDto> types=requestService.listEffectiveMaterialTypes(tenant()); int type= existing==null? types.stream().findFirst().map(MaterialTypeDto::id).orElse(1):existing.materialTypeId(); if(existing==null) return requestService.createMaterialRequest(new MaterialRequestServicePort.CreateMaterialRequestCommand(tenant(),actor(),caseId(),type,trim(title),null,actor(),null,null,null,null,null,LocalDateTime.now(),null,null,"REQUESTED",null,null,null,null,null,null,null,null)); return requestService.updateMaterialRequest(new MaterialRequestServicePort.UpdateMaterialRequestCommand(tenant(),actor(),caseId(),existing.id(),type,trim(title),existing.description(),existing.assignedToUserId(),existing.requestedFromContactId(),existing.requestedFromOrganizationId(),existing.requestedFromText(),existing.requestMethod(),existing.requestedAt(),existing.relevantStartDate(),existing.relevantEndDate(),existing.expectedResponseDate(),existing.nextFollowUpAt(),existing.notes(),existing.rowVer())); }, this::refreshRequests, "Material request saved.")); }
    private void changeRequestStatus(MaterialRequestDetailDto d){ ChoiceDialog<String> c=new ChoiceDialog<>(d.status(), List.of("DRAFT","REQUESTED","FOLLOW_UP_DUE","PARTIALLY_RECEIVED","FULLY_RECEIVED","CLOSED","CANCELLED")); c.setTitle("Change Request Status"); c.showAndWait().ifPresent(s -> mutate(() -> requestService.changeMaterialRequestStatus(new MaterialRequestServicePort.ChangeMaterialRequestStatusCommand(tenant(),actor(),caseId(),d.id(),s,d.requestedAt(),d.firstReceivedAt(),d.fullyReceivedAt(),LocalDateTime.now(),actor(),d.closureReason(),d.rowVer())), this::refreshRequests, "Request status changed.")); }
    private void deleteRequest(MaterialRequestDetailDto d){ mutate(() -> { requestService.deleteMaterialRequest(new MaterialRequestServicePort.DeleteMaterialRequestCommand(tenant(),actor(),caseId(),d.id(),d.rowVer())); return null;}, this::refreshRequests,"Request deleted."); }
    private void openItemDetail(long id){ long cid=caseId(); int tid=tenant(), actor=actor(); run(() -> itemService.getMaterialItem(cid,id,tid,actor).orElseThrow(), this::showItemDetail, "Unable to open material item."); }
    private void showItemDetail(MaterialItemDetailDto d){ Dialog<Void> dlg=dialog("Received Material"); VBox c=new VBox(10, strong(nvl(d.name(),d.materialTypeName())), line("Type / format",d.materialTypeName()+" • "+nvl(d.format(),"Unknown")), line("Source",source(d.sourceContactDisplayName(),d.sourceOrganizationName(),d.sourceText())), line("Location metadata", nvl(d.storageLocation(),"Not provided")+(d.externalLinkId()!=null?" • External reference linked":"")), line("Custody",nvl(d.custodyStatus(),"Unknown")), textBlock("Description",d.description()), textBlock("Physical condition",d.physicalCondition()), textBlock("Return/release notes",d.returnReleaseNotes())); dlg.getDialogPane().setContent(new ScrollPane(c)); ButtonType edit=new ButtonType("Edit Metadata"), link=new ButtonType("Link/Unlink Request"), loc=new ButtonType("Location"), rel=new ButtonType("Record Return/Release"), del=new ButtonType("Delete", ButtonBar.ButtonData.LEFT); dlg.getDialogPane().getButtonTypes().addAll(edit,link,loc,rel,del,ButtonType.CLOSE); button(dlg,edit,()->openItemEditor(d)); button(dlg,link,()->linkItem(d)); button(dlg,loc,()->locationItem(d)); button(dlg,rel,()->releaseItem(d)); button(dlg,del,()->deleteItem(d)); dlg.showAndWait(); }
    private void openItemEditor(MaterialItemDetailDto e){ TextInputDialog t=new TextInputDialog(e==null?"":nvl(e.name(),"")); t.setTitle(e==null?"New Material Item":"Edit Material Item Metadata"); t.showAndWait().ifPresent(name -> mutate(() -> { int type=e==null?requestService.listEffectiveMaterialTypes(tenant()).stream().findFirst().map(MaterialTypeDto::id).orElse(1):e.materialTypeId(); if(e==null) return itemService.createMaterialItem(new MaterialItemServicePort.CreateMaterialItemCommand(tenant(),actor(),caseId(),null,type,"PAPER",trim(name),null,null,null,null,actor(),LocalDateTime.now(),null,null,"UNKNOWN",null,null,null,null,null,null,"IN_FIRM_CUSTODY")); return itemService.updateMaterialItem(new MaterialItemServicePort.UpdateMaterialItemCommand(tenant(),actor(),caseId(),e.id(),type,e.format(),trim(name),e.description(),e.sourceContactId(),e.sourceOrganizationId(),e.sourceText(),e.relevantStartDate(),e.relevantEndDate(),e.completeness(),e.quantityCount(),e.pageCount(),e.fileCount(),e.physicalCondition(),e.rowVer())); }, ()->{refreshItems();refreshRequests();}, "Material item saved.")); }
    private void linkItem(MaterialItemDetailDto d){ if(d.materialRequestId()!=null) mutate(() -> itemService.unlinkMaterialItemFromRequest(new MaterialItemServicePort.UnlinkMaterialItemFromRequestCommand(tenant(),actor(),caseId(),d.id(),d.rowVer())), ()->{refreshItems();refreshRequests();}, "Request link removed."); else if(!requests.isEmpty()) mutate(() -> itemService.linkMaterialItemToRequest(new MaterialItemServicePort.LinkMaterialItemToRequestCommand(tenant(),actor(),caseId(),d.id(),requests.get(0).id(),d.rowVer())), ()->{refreshItems();refreshRequests();}, "Request linked."); }
    private void locationItem(MaterialItemDetailDto d){ TextInputDialog t=new TextInputDialog(nvl(d.storageLocation(),"")); t.setTitle("Location/reference metadata"); t.setHeaderText("This records location/reference metadata only; it does not move, upload, store, or open a file."); t.showAndWait().ifPresent(s -> mutate(() -> itemService.changeMaterialItemLocation(new MaterialItemServicePort.ChangeMaterialItemLocationCommand(tenant(),actor(),caseId(),d.id(),trim(s),d.externalLinkId(),d.rowVer())), this::refreshItems, "Location metadata updated.")); }
    private void releaseItem(MaterialItemDetailDto d){ ChoiceDialog<String> c=new ChoiceDialog<>("RETURNED",List.of("RETURNED","RELEASED","DESTROYED")); c.setTitle("Record Return/Release"); c.setHeaderText("This terminal action records the item as returned or released."); c.showAndWait().ifPresent(s -> mutate(() -> itemService.releaseOrReturnMaterialItem(new MaterialItemServicePort.ReleaseOrReturnMaterialItemCommand(tenant(),actor(),caseId(),d.id(),s,LocalDateTime.now(),null,null,"recipient","HAND_DELIVERY",null,d.rowVer())), this::refreshItems, "Return/release recorded.")); }
    private void deleteItem(MaterialItemDetailDto d){ mutate(() -> { itemService.softDeleteMaterialItem(new MaterialItemServicePort.SoftDeleteMaterialItemCommand(tenant(),actor(),caseId(),d.id(),d.rowVer())); return null;}, this::refreshItems,"Material item deleted."); }
    private <T> void run(Supplier<T> work, java.util.function.Consumer<T> ok, String fail){ executor.submit(() -> { try { T t=work.get(); Platform.runLater(() -> ok.accept(t)); } catch(Exception ex){ Platform.runLater(() -> AppDialogs.showError(owner(), fail, friendly(ex))); } }); }
    private <T> void mutate(Supplier<T> work, Runnable after, String msg){ if(!mutationInFlight.compareAndSet(false,true)) return; executor.submit(() -> { try { T ignored = work.get(); Platform.runLater(() -> { mutationInFlight.set(false); after.run(); AppDialogs.showInfo(owner(), "Materials", msg); }); } catch(Exception ex){ Platform.runLater(() -> { mutationInFlight.set(false); AppDialogs.showError(owner(), "Unable to save materials change.", friendly(ex)); }); } }); }
    private boolean staleRequest(int g,long cid){ return g != requestGeneration.get() || caseId() != cid; } private boolean staleItem(int g,long cid){ return g != itemGeneration.get() || caseId() != cid; } private long caseId(){ return caseIdSupplier.get(); } private int tenant(){ return appState.getShaleClientId(); } private int actor(){ Integer id = appState.getUserId(); return id == null ? 0 : id; } private Window owner(){ return ownerSupplier.get(); }
    private static List<MaterialRequestSummaryDto> orderRequests(List<MaterialRequestSummaryDto> in){ return in.stream().sorted(Comparator.comparing((MaterialRequestSummaryDto r)->terminal(r.status())).thenComparing(r->Optional.ofNullable(r.nextFollowUpAt()).orElse(Optional.ofNullable(r.expectedResponseDate()).orElse(LocalDateTime.MAX))).thenComparingLong(MaterialRequestSummaryDto::id)).toList(); }
    private static List<MaterialItemSummaryDto> orderItems(List<MaterialItemSummaryDto> in){ return in.stream().sorted(Comparator.comparing((MaterialItemSummaryDto i)->Optional.ofNullable(i.receivedAt()).orElse(LocalDateTime.MIN), Comparator.reverseOrder()).thenComparing(i->nvl(i.name(),""), String.CASE_INSENSITIVE_ORDER).thenComparingLong(MaterialItemSummaryDto::id)).toList(); }
    private static boolean terminal(String s){ return Set.of("CLOSED","CANCELLED","FULLY_RECEIVED").contains(nvl(s,"").toUpperCase(Locale.ROOT)); } private static String trim(String s){ return s==null?null:s.trim(); } private static String nvl(String s,String v){ return s==null||s.isBlank()?v:s; } private static String fmt(LocalDateTime t){ return t==null?"Not set":DATE_TIME.format(t); } private static String source(String c,String o,String t){ return nvl(c,nvl(o,nvl(t,"Not provided"))); } private static String counts(MaterialItemSummaryDto i){ return "Qty "+Optional.ofNullable(i.quantityCount()).map(Object::toString).orElse("—")+" • Pages "+Optional.ofNullable(i.pageCount()).map(Object::toString).orElse("—")+" • Files "+Optional.ofNullable(i.fileCount()).map(Object::toString).orElse("—"); }
    private static Label title(String s){ Label l=new Label(s); l.setStyle("-fx-font-size:16px;-fx-font-weight:bold;"); return l;} private static Label strong(String s){ Label l=new Label(s); l.setStyle("-fx-font-weight:bold;"); l.setWrapText(true); return l;} private static Label muted(String s){ Label l=new Label(s); l.setStyle("-fx-opacity:.75;"); l.setWrapText(true); return l;} private static Label pill(String s){ Label l=new Label(s); l.getStyleClass().add("shale-status-pill"); return l;} private static Label line(String k,String v){ Label l=new Label(k+": "+v); l.setWrapText(true); return l;} private static Label textBlock(String k,String v){ return line(k, nvl(v,"Not provided")); } private static Region typeDot(String key){ Region r=new Region(); r.setMinSize(10,10); r.setMaxSize(10,10); r.setStyle("-fx-background-radius:99;-fx-background-color:#6b7280;"); return r;} private static Button primary(String s){ Button b=new Button(s); b.getStyleClass().addAll("app-toolbar-button","app-toolbar-button-primary"); return b;} private static VBox card(){ VBox v=new VBox(6); v.setPadding(new Insets(10)); v.getStyleClass().addAll("shale-card","entity-card"); return v;} private static VBox section(Label t, Button b, Label s, VBox list){ HBox h=new HBox(8,t,new Region(),b); HBox.setHgrow(h.getChildren().get(1),Priority.ALWAYS); h.setAlignment(Pos.CENTER_LEFT); ScrollPane sp=new ScrollPane(list); sp.setFitToWidth(true); sp.getStyleClass().add("transparent-scroll"); VBox v=new VBox(10,h,s,sp); VBox.setVgrow(sp,Priority.ALWAYS); v.setPadding(new Insets(10)); v.getStyleClass().add("shale-surface-section"); return v;} private static void show(Label l,String s){ l.setText(s); l.setVisible(true); l.setManaged(true);} private static void hide(Label l){ l.setVisible(false); l.setManaged(false);} private static Dialog<Void> dialog(String title){ Dialog<Void> d=new Dialog<>(); d.setTitle(title); d.getDialogPane().setPrefSize(720,620); return d;} private static void button(Dialog<?> d, ButtonType t, Runnable r){ Node n=d.getDialogPane().lookupButton(t); n.addEventFilter(javafx.event.ActionEvent.ACTION,e->{e.consume(); r.run();}); } private void showError(String s){ AppDialogs.showError(owner(),"Materials",s);} private static String friendly(Exception ex){ String m=String.valueOf(ex.getMessage()); return m.toLowerCase(Locale.ROOT).contains("rowver")||m.toLowerCase(Locale.ROOT).contains("concurr") ? "This record changed by another user. Reload and try again." : "The materials change could not be completed. Please review the fields and try again."; }
}
