package com.shale.ui.controller;

import static com.shale.core.service.OrganizationServicePort.*;

import java.text.Normalizer;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import java.util.function.Supplier;

import com.shale.core.service.OrganizationServicePort;
import com.shale.ui.component.dialog.AppDialogs;
import com.shale.ui.state.AppState;
import com.shale.ui.util.*;
import javafx.application.Platform;
import javafx.geometry.Orientation;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;

/** Administrator-only Settings surface for Organization Type definitions. */
public final class OrganizationTypeAdminPane {
    static final double CARD_MIN_HEIGHT=76,CARD_PREF_HEIGHT=84,CARD_MAX_HEIGHT=94,DIALOG_MIN_WIDTH=500,DIALOG_PREF_WIDTH=580;
    private final OrganizationServicePort service; private final AppState state;
    private final ExecutorService worker=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"organization-type-settings");t.setDaemon(true);return t;});
    private final AtomicBoolean loading=new AtomicBoolean(),mutating=new AtomicBoolean(),disposed=new AtomicBoolean();
    private final AtomicInteger generation=new AtomicInteger();
    private final VBox root=new VBox(14),active=new VBox(8),inactive=new VBox(8),removed=new VBox(8);
    private final Label status=new Label(); private final Button add=button("Add Organization Type",ControlStyles.Purpose.PRIMARY),refresh=button("Refresh",ControlStyles.Purpose.SECONDARY);
    private volatile List<OrganizationTypeDefinition> rows=List.of(); private volatile String refreshedMessage;

    public OrganizationTypeAdminPane(OrganizationServicePort service,AppState state){this.service=Objects.requireNonNull(service);this.state=Objects.requireNonNull(state);
        add.setId("organization-type-add");refresh.setId("organization-type-refresh");status.setId("organization-type-status");status.getStyleClass().add("contact-classification-status");status.setWrapText(true);
        active.setId("organization-type-active-list");inactive.setId("organization-type-inactive-list");removed.setId("organization-type-removed-list");
        add.setOnAction(e->editor(null));refresh.setOnAction(e->requestLoad());
        FlowPane toolbar=new FlowPane(Orientation.HORIZONTAL,8,8,add,refresh);toolbar.getStyleClass().add("contact-classification-toolbar");
        root.getStyleClass().add("contact-classification-admin");root.getChildren().setAll(toolbar,status,section("Active / effective",active),section("Inactive tenant definitions",inactive),section("Removed tenant definitions",removed));
        root.sceneProperty().addListener((o,a,b)->{if(a!=null&&b==null)dispose();});
        if(!state.isAdmin()){root.setDisable(true);message("Access restricted — administrator access is required.","error");}else requestLoad();
    }
    public Node node(){return root;}
    private VBox section(String title,VBox content){Label label=new Label(title);label.getStyleClass().add("app-dialog-field-label");return new VBox(8,label,content);}
    private void requestLoad(){generation.incrementAndGet();loadLatest();}
    private void loadLatest(){if(disposed.get()||!state.isAdmin()||!loading.compareAndSet(false,true))return;int g=generation.get(),tenant=tenant(),actor=actor();busy(true);message(rows.isEmpty()?"Loading Organization Types…":"Refreshing Organization Types…","loading");worker.submit(()->{try{if(Platform.isFxApplicationThread())throw new IllegalStateException("Settings reads must run off the JavaFX thread.");var loaded=service.listOrganizationTypesForAdministration(tenant,actor);Platform.runLater(()->finish(g,loaded,null));}catch(RuntimeException ex){Platform.runLater(()->finish(g,null,ex));}});}
    private void finish(int g,List<OrganizationTypeDefinition> loaded,RuntimeException failure){loading.set(false);if(disposed.get())return;if(g!=generation.get()){loadLatest();return;}busy(false);if(failure!=null){message("Load failed — Organization Types could not be loaded. Choose Refresh to try again.","error");return;}rows=List.copyOf(loaded);String success=refreshedMessage;refreshedMessage=null;message(success==null?"":success,"ready");render();}
    private void render(){Map<String,OrganizationTypeDefinition> globals=new HashMap<>(),tenants=new HashMap<>();for(var r:rows){if(r.shaleClientId()==null)globals.put(r.systemKey(),r);else tenants.put(r.systemKey(),r);}List<Node> a=new ArrayList<>(),i=new ArrayList<>(),d=new ArrayList<>();
        for(var r:rows){boolean override=r.shaleClientId()!=null&&globals.containsKey(r.systemKey());if(r.deleted()){if(r.shaleClientId()!=null)d.add(card(r,override,false));continue;}if(r.shaleClientId()==null&&tenants.containsKey(r.systemKey())&&!tenants.get(r.systemKey()).deleted())continue;if(r.active())a.add(card(r,override,true));else if(r.shaleClientId()!=null)i.add(card(r,override,false));}
        active.getChildren().setAll(a.isEmpty()?List.of(empty("No active Organization Types.")):a);inactive.getChildren().setAll(i.isEmpty()?List.of(empty("No inactive tenant definitions.")):i);removed.getChildren().setAll(d.isEmpty()?List.of(empty("No removed tenant definitions.")):d);}
    private Node empty(String text){Label l=new Label(text);l.getStyleClass().addAll("contact-classification-empty","contact-classification-state-message");return l;}
    Node card(OrganizationTypeDefinition r,boolean override,boolean effective){Region swatch=new Region();swatch.getStyleClass().add("contact-classification-color-swatch");swatch.setAccessibleText("Organization Type color "+r.color());String css=ColorUtil.toCssBackgroundColorOrNull(r.color());if(css!=null)swatch.setStyle("-fx-background-color: "+css+";");Label name=new Label(r.name());name.setTextOverrun(OverrunStyle.ELLIPSIS);name.setMinWidth(0);name.setMaxWidth(Double.MAX_VALUE);name.setTooltip(new Tooltip(r.name()));name.getStyleClass().add("contact-classification-card-title");FlowPane badges=new FlowPane(Orientation.HORIZONTAL,6,4,badge(r.shaleClientId()==null?"Global":override?"Customized for this firm":"Tenant-owned"),badge(r.deleted()?"Removed":r.active()?(effective?"Effective":"Active"):"Inactive"));badges.getStyleClass().add("organization-type-card-badges");HBox heading=new HBox(8,name,badges);heading.setAlignment(Pos.CENTER_LEFT);HBox.setHgrow(name,Priority.ALWAYS);Label key=new Label("Internal key: "+r.systemKey()+"  •  Sort order: "+r.sortOrder());key.setTextOverrun(OverrunStyle.ELLIPSIS);key.setMinWidth(0);key.setMaxWidth(Double.MAX_VALUE);key.getStyleClass().add("contact-classification-metadata");VBox details=new VBox(3,heading);details.setMinWidth(0);details.setMaxWidth(Double.MAX_VALUE);String description=r.description();if(description!=null&&!description.isBlank()){Label desc=new Label(description);desc.setTextOverrun(OverrunStyle.ELLIPSIS);desc.setMinWidth(0);desc.setMaxWidth(Double.MAX_VALUE);desc.setTooltip(new Tooltip(description));desc.getStyleClass().add("contact-classification-description");details.getChildren().add(desc);}details.getChildren().add(key);HBox actions=new HBox(6);actions.setAlignment(Pos.CENTER_RIGHT);actions.setMinWidth(Region.USE_PREF_SIZE);actions.getStyleClass().add("organization-type-card-actions");if(r.shaleClientId()==null)actions.getChildren().add(action("Customize for this firm",()->editor(r),ControlStyles.Purpose.SECONDARY));else if(r.deleted())actions.getChildren().add(action("Restore",()->lifecycle(r,"restore",override),ControlStyles.Purpose.SECONDARY));else{actions.getChildren().add(action("Edit",()->editor(r),ControlStyles.Purpose.SECONDARY));actions.getChildren().add(action(r.active()?"Deactivate":"Activate",()->lifecycle(r,r.active()?"deactivate":"activate",override),ControlStyles.Purpose.SECONDARY));actions.getChildren().add(action("Remove",()->lifecycle(r,"remove",override),ControlStyles.Purpose.DANGER));}HBox card=new HBox(10,swatch,details,actions);card.setAlignment(Pos.CENTER_LEFT);card.setFillHeight(false);card.setMinHeight(CARD_MIN_HEIGHT);card.setPrefHeight(CARD_PREF_HEIGHT);card.setMaxHeight(CARD_MAX_HEIGHT);HBox.setHgrow(details,Priority.ALWAYS);card.getStyleClass().addAll("shale-card-surface","contact-classification-card","organization-type-definition-card");if(!r.active()||r.deleted())card.getStyleClass().add("contact-classification-card-subdued");return card;}
    private void lifecycle(OrganizationTypeDefinition r,String op,boolean override){if(mutating.get()||r.shaleClientId()==null||!state.isAdmin())return;boolean confirmation=!op.equals("activate");if(confirmation){String effect=op.equals("deactivate")?"This type will not be available for new assignments. Existing Organization assignments are preserved for historical display.":op.equals("remove")?(override?"The global definition will become effective again. ":"")+"The tenant definition will be soft-removed. Existing Organization assignments remain in historical data.":"The definition returns to its saved active or inactive state. Historical Organization assignments are not changed.";if(!AppDialogs.showConfirmation(owner(),"Organization Types",capitalize(op)+" “"+r.name()+"”?",effect,capitalize(op),op.equals("remove")||op.equals("deactivate")?AppDialogs.DialogActionKind.DANGER:AppDialogs.DialogActionKind.PRIMARY))return;}
        OrganizationTypeLifecycleCommand c=new OrganizationTypeLifecycleCommand(r.organizationTypeId(),tenant(),actor(),op.equals("activate")||op.equals("restore"),r.rowVer());mutate(()->switch(op){case "activate","deactivate"->service.setOrganizationTypeActive(c);case "remove"->service.removeOrganizationType(c);case "restore"->service.restoreOrganizationType(c);default->throw new IllegalArgumentException();},null);}
    private void editor(OrganizationTypeDefinition existing){if(!state.isAdmin()||mutating.get())return;boolean override=existing!=null&&existing.shaleClientId()==null;Dialog<Void> dialog=new Dialog<>();dialog.setTitle(existing==null?"Add Organization Type":override?"Customize Organization Type":"Edit Organization Type");if(owner()!=null)dialog.initOwner(owner());dialog.getDialogPane().getStyleClass().addAll("secondary-window-shell","contact-classification-dialog","organization-type-dialog");dialog.getDialogPane().setMinWidth(DIALOG_MIN_WIDTH);dialog.getDialogPane().setPrefWidth(DIALOG_PREF_WIDTH);dialog.getDialogPane().getButtonTypes().setAll(ButtonType.OK,ButtonType.CANCEL);
        TextField name=field(existing==null?"":existing.name()),key=field(existing==null?"":existing.systemKey()),order=field(existing==null?Integer.toString(appendOrder()):Integer.toString(existing.sortOrder()));TextArea description=new TextArea(existing==null||existing.description()==null?"":existing.description());ContactClassificationAdminPane.configureDescription(description);ColorPicker color=new ColorPicker(Color.web(existing==null?"#6C757D":existing.color()));ControlStyles.formControl(color);if(existing==null)name.textProperty().addListener((o,a,b)->{if(key.getText().isBlank()||key.getText().equals(systemKey(a)))key.setText(systemKey(b));});Label context=new Label(override?"Customization creates a tenant-specific version using the same stable identity; the global definition remains unchanged.":existing==null?"The internal key is generated from the initial name. Adjust it before saving if another current or historical definition uses it.":"The internal key is immutable after creation.");context.setWrapText(true);Label error=new Label();error.getStyleClass().add("contact-classification-editor-error");GridPane form=editorForm(name,description,color,order,key,existing==null);VBox body=new VBox(12,context,form,error);body.getStyleClass().add("contact-classification-dialog-body");dialog.getDialogPane().setContent(body);Button save=(Button)dialog.getDialogPane().lookupButton(ButtonType.OK);save.setText("Save");ControlStyles.apply(save,ControlStyles.Purpose.PRIMARY);ControlStyles.apply((Button)dialog.getDialogPane().lookupButton(ButtonType.CANCEL),ControlStyles.Purpose.SECONDARY);save.addEventFilter(javafx.event.ActionEvent.ACTION,e->{e.consume();String validation=validate(name.getText(),description.getText(),key.getText(),order.getText());if(validation!=null){error.setText(validation);return;}int sort=Integer.parseInt(order.getText());Supplier<OrganizationTypeMutationResult> operation=existing==null||override?()->service.createOrganizationType(new CreateOrganizationTypeCommand(tenant(),actor(),override?existing.systemKey():key.getText(),override?existing.organizationTypeId():null,name.getText().trim(),description.getText(),hex(color.getValue()),sort,true)):()->service.updateOrganizationType(new UpdateOrganizationTypeCommand(existing.organizationTypeId(),tenant(),actor(),name.getText().trim(),description.getText(),hex(color.getValue()),sort,existing.rowVer()));save.setDisable(true);error.setText("Saving changes…");mutate(operation,ex->{save.setDisable(false);error.setText(friendly(ex));if(stale(ex)){dialog.close();requestLoad();}},dialog::close);});dialog.show();}
    static GridPane editorForm(TextField name,TextArea description,ColorPicker color,TextField order,TextField key,boolean creating){key.setEditable(creating);if(!creating)key.getStyleClass().add("contact-classification-readonly");GridPane form=new GridPane();form.setHgap(12);form.setVgap(10);form.getStyleClass().addAll("contact-classification-form","organization-type-editor-form");ColumnConstraints labels=new ColumnConstraints(112,112,Double.MAX_VALUE);labels.setHgrow(Priority.NEVER);labels.setFillWidth(false);ColumnConstraints controls=new ColumnConstraints();controls.setMinWidth(240);controls.setHgrow(Priority.ALWAYS);controls.setFillWidth(true);form.getColumnConstraints().setAll(labels,controls);for(String text:List.of("Name","Description","Color","Sort order","Internal key")){Label label=new Label(text);label.setMinWidth(Region.USE_PREF_SIZE);label.getStyleClass().add("organization-type-editor-label");form.add(label,0,form.getRowCount());}form.add(name,1,0);form.add(description,1,1);form.add(color,1,2);form.add(order,1,3);form.add(key,1,4);for(Node control:List.of(name,description,color,order,key)){GridPane.setHgrow(control,Priority.ALWAYS);if(control instanceof Region region)region.setMaxWidth(Double.MAX_VALUE);}return form;}
    private void mutate(Supplier<OrganizationTypeMutationResult> op,java.util.function.Consumer<RuntimeException> failure){mutate(op,failure,null);}private void mutate(Supplier<OrganizationTypeMutationResult> op,java.util.function.Consumer<RuntimeException> failure,Runnable success){if(!state.isAdmin()||disposed.get()||!mutating.compareAndSet(false,true))return;busy(true);message("Applying Organization Type change…","loading");worker.submit(()->{try{OrganizationTypeMutationResult result=op.get();Platform.runLater(()->{mutating.set(false);if(disposed.get())return;busy(false);refreshedMessage="Organization Type saved ("+result.systemKey()+").";if(success!=null)success.run();requestLoad();});}catch(RuntimeException ex){Platform.runLater(()->{mutating.set(false);if(disposed.get())return;busy(false);LOG.warn("Organization Type Settings mutation failed",ex);if(failure!=null)failure.accept(ex);else{message(friendly(ex),stale(ex)?"stale":"error");if(stale(ex))requestLoad();}});}});}
    private static final org.slf4j.Logger LOG=org.slf4j.LoggerFactory.getLogger(OrganizationTypeAdminPane.class);
    private void busy(boolean v){add.setDisable(v);refresh.setDisable(v);active.setDisable(v);inactive.setDisable(v);removed.setDisable(v);}private void message(String s,String kind){status.setText(s);status.setVisible(!s.isBlank());status.setManaged(!s.isBlank());status.getStyleClass().removeIf(x->x.startsWith("contact-classification-status-"));status.getStyleClass().add("contact-classification-status-"+kind);}
    private int tenant(){Integer x=state.getShaleClientId();if(x==null||x<=0)throw new SecurityException("A tenant session is required.");return x;}private int actor(){Integer x=state.getUserId();if(x==null||x<=0)throw new SecurityException("An authenticated administrator is required.");return x;}private javafx.stage.Window owner(){return root.getScene()==null?null:root.getScene().getWindow();}private int appendOrder(){return rows.stream().mapToInt(OrganizationTypeDefinition::sortOrder).max().orElse(-1)+1;}void dispose(){if(disposed.compareAndSet(false,true))worker.shutdownNow();}
    static String systemKey(String value){if(value==null)return "";return Normalizer.normalize(value,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","_").replaceAll("^_+|_+$","");}static String validate(String name,String description,String key,String order){if(name==null||name.isBlank())return "Name is required.";if(name.trim().length()>100)return "Name must be at most 100 characters.";if(description!=null&&description.trim().length()>500)return "Description must be at most 500 characters.";if(key==null||key.length()>128||!key.matches("[a-z][a-z0-9]*(?:_[a-z0-9]+)*"))return "Internal key must use lowercase snake_case.";try{if(Integer.parseInt(order)<0)return "Sort Order must be a nonnegative integer.";}catch(Exception e){return "Sort Order must be a nonnegative integer.";}return null;}private static String hex(Color c){return String.format("#%02X%02X%02X",Math.round(c.getRed()*255),Math.round(c.getGreen()*255),Math.round(c.getBlue()*255));}private static boolean stale(Throwable e){for(Throwable x=e;x!=null;x=x.getCause())if(x.getMessage()!=null&&(x.getMessage().contains("changed")||x.getMessage().contains("reload")))return true;return false;}private static String friendly(Throwable e){String m=e.getMessage();if(stale(e))return "This definition changed on another workstation. The current list has been reloaded; review it before trying again.";if(e instanceof SecurityException)return "You are not authorized to manage Organization Types for this tenant.";if(m!=null&&m.contains("conflicts with existing data"))return "That internal key is already used by a current or historical Organization Type. Adjust the key before saving.";if(m!=null&&(m.contains("SystemKey")||m.contains("already uses")||m.contains("not found")||m.contains("another tenant")||m.contains("read-only")||m.contains("Color")||m.contains("Name")))return m;return "The Organization Type could not be saved. Check your connection and try again.";}private static String capitalize(String s){return Character.toUpperCase(s.charAt(0))+s.substring(1);}private static Label badge(String text){Label l=new Label(text);l.getStyleClass().addAll("metadata-chip","contact-classification-badge");return l;}private static Button button(String text,ControlStyles.Purpose p){Button b=new Button(text);ControlStyles.apply(b,p,ControlStyles.Size.STANDARD);return b;}private Button action(String text,Runnable run,ControlStyles.Purpose p){Button b=new Button(text);ControlStyles.apply(b,p,ControlStyles.Size.SMALL);b.setAccessibleText(text+" Organization Type");b.setOnAction(e->run.run());return b;}private static TextField field(String value){TextField f=new TextField(value);ControlStyles.formControl(f);return f;}
}
