package com.shale.server.runtime;

import static org.junit.jupiter.api.Assertions.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import com.shale.core.dto.UserSessionView;
import com.shale.core.model.ClientType;

final class RememberedDesktopSessionTest {
 @Test void checkedEnrollmentAndRestoreRotateOpaqueCredentialWithoutExtendingDeadline(){var fixture=new Fixture();var issued=fixture.service.issueRememberedDesktop(fixture.principal,44L,fixture.installation,fixture.remembers);assertNotNull(issued.rememberCredential());assertFalse(issued.accessToken().equals(issued.rememberCredential()));Instant deadline=issued.rememberExpiresAt();String replacement=ServerAuthSessionService.RememberedSession.newSecret();var restored=fixture.service.restoreDesktop(issued.rememberCredential(),replacement,fixture.installation,fixture.remembers).orElseThrow();assertEquals(replacement,restored.rememberCredential());assertEquals(deadline,restored.rememberExpiresAt(),"rotation must preserve the absolute 30-day deadline");assertTrue(fixture.service.restoreDesktop(issued.rememberCredential(),ServerAuthSessionService.RememberedSession.newSecret(),fixture.installation,fixture.remembers).isEmpty(),"a consumed credential must be rejected as replay");}
 @Test void wrongInstallationRevocationExpiryAndDisabledOwnerAreRejected(){var f=new Fixture();var issued=f.service.issueRememberedDesktop(f.principal,null,f.installation,f.remembers);assertTrue(f.service.restoreDesktop(issued.rememberCredential(),ServerAuthSessionService.RememberedSession.newSecret(),UUID.randomUUID(),f.remembers).isEmpty());f.remembers.active=false;assertTrue(f.service.restoreDesktop(issued.rememberCredential(),ServerAuthSessionService.RememberedSession.newSecret(),f.installation,f.remembers).isEmpty(),"inactive/revoked authority must fail closed");}
 static final class Fixture{final ServerPrincipal principal=new ServerPrincipal(9,7,"owner@test");final UUID installation=UUID.randomUUID();final Sessions sessions=new Sessions();final Remembers remembers=new Remembers();final ServerAuthSessionService service;Fixture(){var tokens=new ShaleAuthTokenService("test-auth-token-secret-that-is-long-enough",3600,Clock.systemUTC());service=new ServerAuthSessionService(tokens,sessions,new DurableSessionTokenValidator(sessions),new LegacyTokenCompatibilityPolicy(Instant.now(),3600,Clock.systemUTC()),new InMemoryTokenRevocationStore());}}
 static final class Remembers implements RememberCredentialStore{byte[] hash;UUID installation,session;ServerPrincipal principal;Instant deadline;boolean active=true;public void create(ServerPrincipal p,UUID s,UUID i,byte[] h,Instant d){principal=p;session=s;installation=i;hash=h;deadline=d;}public Optional<Record> rotate(byte[] old,UUID i,byte[] replacement,UUID jti,Instant now){if(!active||!i.equals(installation)||!Arrays.equals(old,hash)||!now.isBefore(deadline))return Optional.empty();hash=replacement;return Optional.of(new Record(principal,session,i,deadline,true,false));}public void deleteForSession(ServerPrincipal p,UUID s){active=false;}}
 static final class Sessions implements DurableSessionStore{UserSessionView value;public UserSessionView create(ServerPrincipal p,ClientType c,Long i,UUID j,Instant e){return value=new UserSessionView(1,UUID.randomUUID(),c,i,j,Instant.now(),e,null,null,null);}public Optional<UserSessionView> find(ServerPrincipal p,UUID s){return Optional.ofNullable(value).filter(v->v.sessionId().equals(s));}public UserSessionView rotate(ServerPrincipal p,UUID s,UUID expected,UUID replacement,Instant e){if(value==null||!value.currentAccessJti().equals(expected)||value.revokedAt()!=null)throw new IllegalStateException();return value=new UserSessionView(value.id(),s,value.clientType(),value.applicationInstanceId(),replacement,value.issuedAt(),e,Instant.now(),null,null);}public UserSessionView revoke(ServerPrincipal p,UUID s,String r){value=new UserSessionView(value.id(),s,value.clientType(),value.applicationInstanceId(),value.currentAccessJti(),value.issuedAt(),value.expiresAt(),value.lastRefreshedAt(),Instant.now(),r);return value;}}
}
