package com.shale.server.runtime;
import static org.junit.jupiter.api.Assertions.*;import java.nio.file.*;import org.junit.jupiter.api.Test;
class SessionManagementContractTest{
	private static String source(String path)throws Exception{return Files.readString(Path.of("src/main/java",path));}
	@Test void serviceKeepsEveryReadAndMutationTenantQualifiedSetBasedAndAudited()throws Exception{String s=source("com/shale/server/runtime/SessionManagementService.java");for(String x:new String[]{"WHERE s.ShaleClientId=?","AND s.UserId=?","SessionId<>?","ORDER BY s.IssuedAt DESC,s.Id DESC","requireEligibleActor","requireAdmin","SessionSecurityAuditLog","c.rollback()"})assertTrue(s.contains(x),x);assertFalse(s.contains("ApplicationInstances"));assertFalse(s.contains("PubSub"));assertEquals(1,count(s,"if(admin)appendAudit(c,actor,\"ADMIN_SESSION_LIST\""),"one bounded read audit must be appended per query, never per row");}
	@Test void publicProjectionExcludesSecretsAndInternalIdentity()throws Exception{String s=source("com/shale/server/dto/UserSessionResponse.java");for(String x:new String[]{"currentAccessJti","accessToken","rowVer","shaleClientId","long id"})assertFalse(s.contains(x),x);}
	@Test void adminProjectionJoinsOwnerIdentityWithoutPerRowLookup()throws Exception{String s=source("com/shale/server/runtime/SessionManagementService.java");assertTrue(s.contains("JOIN dbo.Users u"));assertTrue(s.contains("u.name_first"));assertTrue(s.contains("u.name_last"));assertTrue(s.contains("u.email"));assertFalse(s.contains("for(UserSessionResponse"));}
	@Test void invalidationIsStrictlyAfterCommitAndFailureIsBestEffort()throws Exception{String s=source("com/shale/server/runtime/SessionManagementService.java");assertTrue(s.contains("publishAfterCommit(actor,mutate("),"publication must consume only a successfully returned committed mutation");assertTrue(s.contains("c.commit();return List.copyOf(changed)"));assertTrue(s.contains("catch(RuntimeException failure)"));assertTrue(s.contains("OUTPUT INSERTED.SessionId"),"bulk fanout must reuse mutation output rather than N+1 reads");}
	private static int count(String s,String x){int n=0,p=0;while((p=s.indexOf(x,p))>=0){n++;p+=x.length();}return n;}
}
