package com.shale.desktop.instance;
import static org.junit.jupiter.api.Assertions.*;import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import org.junit.jupiter.api.Test;import com.shale.core.dto.ApplicationInstanceView;import com.shale.core.model.*;import com.shale.core.service.*;
class ApplicationInstanceHeartbeatLifecycleTest{
 @Test void jitterIsBoundedLatestActivityIsReadAtSendTimeAndNoImmediateRetry(){var service=new Recording();var scheduler=new FakeScheduler();var activity=new AtomicReference<Instant>();var lifecycle=new ApplicationInstanceHeartbeatLifecycle(service,scheduler,()->10,()->"1.0.130");lifecycle.start(7,9,3,()->Optional.ofNullable(activity.get()));assertEquals(70,scheduler.delay);activity.set(Instant.parse("2026-09-29T14:20:00Z"));scheduler.run();assertEquals(activity.get(),service.activity);assertEquals(1,service.calls);assertEquals(70,scheduler.delay);lifecycle.stop();}
 @Test void durableResultStopsAndGenerationPreventsOldCallbackFromStoppingReplacement(){var service=new Recording();var scheduler=new FakeScheduler();var lifecycle=new ApplicationInstanceHeartbeatLifecycle(service,scheduler,()->-10,()->"1.0.130");lifecycle.start(7,9,3,Optional::<Instant>empty);Runnable old=scheduler.task;lifecycle.start(7,10,4,Optional::<Instant>empty);old.run();assertEquals(0,service.calls);assertEquals(50,scheduler.delay);service.durable=true;scheduler.run();assertEquals(1,service.calls);scheduler.run();assertEquals(1,service.calls);}
 @Test void lifecycleUsesSingleThreadedCompletionBeforeRescheduling(){var service=new Recording();var scheduler=new FakeScheduler();var lifecycle=new ApplicationInstanceHeartbeatLifecycle(service,scheduler,()->0,()->"1.0.130");lifecycle.start(7,9,3,Optional::<Instant>empty);Runnable first=scheduler.task;scheduler.task=null;first.run();assertEquals(1,service.maxConcurrent.get());assertNotNull(scheduler.task);}
 static final class Recording implements ApplicationInstanceServicePort{int calls;Instant activity;boolean durable;AtomicInteger concurrent=new AtomicInteger(),maxConcurrent=new AtomicInteger();public ApplicationInstanceView enroll(int t,int u,UUID m,ClientType c,SemanticVersion v){throw new UnsupportedOperationException();}public ApplicationInstanceView end(int t,int u,long id){throw new UnsupportedOperationException();}public ApplicationInstanceView heartbeat(int t,int u,long id,SemanticVersion v,Instant a){calls++;activity=a;maxConcurrent.accumulateAndGet(concurrent.incrementAndGet(),Math::max);concurrent.decrementAndGet();if(durable)throw new SecurityException();return new ApplicationInstanceView(id,UUID.randomUUID(),ClientType.DESKTOP,v,Instant.EPOCH,null,Instant.EPOCH,null);}}
 static final class FakeScheduler extends AbstractExecutorService implements ScheduledExecutorService{Runnable task;long delay;boolean down;void run(){Runnable r=task;task=null;if(r!=null)r.run();}public ScheduledFuture<?> schedule(Runnable r,long d,TimeUnit u){task=r;delay=u.toSeconds(d);return new FutureStub();}public <V>ScheduledFuture<V> schedule(Callable<V> c,long d,TimeUnit u){throw new UnsupportedOperationException();}public ScheduledFuture<?> scheduleAtFixedRate(Runnable r,long a,long b,TimeUnit u){throw new UnsupportedOperationException();}public ScheduledFuture<?> scheduleWithFixedDelay(Runnable r,long a,long b,TimeUnit u){throw new UnsupportedOperationException();}public void shutdown(){down=true;}public List<Runnable> shutdownNow(){down=true;return List.of();}public boolean isShutdown(){return down;}public boolean isTerminated(){return down;}public boolean awaitTermination(long t,TimeUnit u){return true;}public void execute(Runnable r){r.run();}}
 static final class FutureStub implements ScheduledFuture<Object>{boolean cancelled;public long getDelay(TimeUnit u){return 0;}public int compareTo(Delayed d){return 0;}public boolean cancel(boolean b){cancelled=true;return true;}public boolean isCancelled(){return cancelled;}public boolean isDone(){return false;}public Object get(){return null;}public Object get(long t,TimeUnit u){return null;}}
}
