package com.shale.desktop.instance;
import static org.junit.jupiter.api.Assertions.*;
import java.time.Instant;import java.util.UUID;import org.junit.jupiter.api.*;
import com.shale.core.dto.ApplicationInstanceView;import com.shale.core.model.*;import com.shale.core.service.ApplicationInstanceServicePort;import com.shale.data.runtime.RuntimeSessionService;import com.shale.desktop.identity.*;import com.shale.desktop.live.LiveEventDispatcher;import com.shale.desktop.runtime.DesktopRuntimeSessionProvider;import com.shale.desktop.ui.DesktopUiRuntimeBridge;
class DesktopApplicationInstanceLifecycleTest{
	String previous;
	@BeforeEach void version(){previous=System.getProperty("APP_VERSION");System.setProperty("APP_VERSION","1.0.130");}
	@AfterEach void restore(){if(previous==null)System.clearProperty("APP_VERSION");else System.setProperty("APP_VERSION",previous);}
	@Test void loginEnrollsStableMachineAndLogoutEndsAndClears(){var service=new Recording();var bridge=bridge(MachineIdentityResult.available(service.machine),service);bridge.onLoginSuccess(31,41,"a@test");assertEquals(1,service.enrolls);assertEquals("1.0.130",service.version.toString());assertTrue(bridge.currentApplicationInstance().isPresent());bridge.onLogout();assertEquals(1,service.ends);assertTrue(bridge.currentApplicationInstance().isEmpty());}
	@Test void unavailableIdentityAndEnrollmentFailureNeverBlockLogin(){var unavailable=new Recording();bridge(MachineIdentityResult.unavailable(MachineIdentityResult.Failure.STORAGE_ACCESS_FAILED),unavailable).onLoginSuccess(31,41,"a@test");assertEquals(0,unavailable.enrolls);var failing=new Recording();failing.failEnroll=true;assertDoesNotThrow(()->bridge(MachineIdentityResult.available(failing.machine),failing).onLoginSuccess(31,41,"a@test"));}
	@Test void secondLoginGetsNewInstanceAndShutdownEndFailureIsBestEffort(){var service=new Recording();var bridge=bridge(MachineIdentityResult.available(service.machine),service);bridge.onLoginSuccess(31,41,"a@test");bridge.onLogout();bridge.onLoginSuccess(32,41,"b@test");assertEquals(2,service.enrolls);service.failEnd=true;assertDoesNotThrow(bridge::onShutdown);assertTrue(bridge.currentApplicationInstance().isEmpty());}
	private static DesktopUiRuntimeBridge bridge(MachineIdentityResult identity,Recording service){var provider=new DesktopRuntimeSessionProvider();var bridge=new DesktopUiRuntimeBridge(new LiveEventDispatcher(),provider,"",identity,service);bridge.setRuntimeSessionService(new RuntimeSessionService(null));return bridge;}
	static final class Recording implements ApplicationInstanceServicePort{final UUID machine=UUID.randomUUID();int enrolls,ends;long next;boolean failEnroll,failEnd;SemanticVersion version;public ApplicationInstanceView enroll(int t,int u,UUID m,ClientType c,SemanticVersion v){enrolls++;version=v;if(failEnroll)throw new IllegalStateException();return new ApplicationInstanceView(++next,m,c,v,Instant.EPOCH,null);}public ApplicationInstanceView end(int t,int u,long id){ends++;if(failEnd)throw new IllegalStateException();return new ApplicationInstanceView(id,machine,ClientType.DESKTOP,version,Instant.EPOCH,Instant.EPOCH.plusSeconds(1));}}
}
