package com.shale.ui.controller;
import static org.junit.jupiter.api.Assertions.*;import java.nio.file.*;import org.junit.jupiter.api.Test;
final class AdminSessionsPaneContractTest{
 private static final Path SOURCE=Path.of("src/main/java/com/shale/ui/controller/AdminSessionsPane.java");
 @Test void boundedServerFiltersAndPagingAreExplicit()throws Exception{String s=Files.readString(SOURCE);assertTrue(s.contains("PAGE_SIZE=50"));for(String x:new String[]{"userId()","clientType()","activeOnly()","since()","Previous","Next","Clear filters"})assertTrue(s.contains(x),x);assertFalse(s.contains("UserSessions"));}
 @Test void presentationUsesOnlySafeSecurityFieldsAndFactualStates()throws Exception{String s=Files.readString(SOURCE);for(String x:new String[]{"Active","Revoked","Expired","Signed in","Last refreshed","Expires","Reason","Revoke session"})assertTrue(s.contains(x),x);for(String x:new String[]{"JWT","JTI","machine UUID","tenant ID","IP address","location","online","working","idle","away"})assertFalse(s.contains("\""+x),x);}
 @Test void currentSessionAndStaleIdentityAreProtected()throws Exception{String s=Files.readString(SOURCE);assertTrue(s.contains("if(target.currentSession()||loading)return"));assertTrue(s.contains("Use ordinary logout to end this session."));assertTrue(s.contains("token!=generation.get()"));assertTrue(s.contains("!who.equals(identity())"));assertTrue(s.contains("!state.isAdmin()"));assertTrue(s.contains("rows.getChildren().clear()"));}
 @Test void revocationRequiresConfirmationAndAuthoritativeReload()throws Exception{String s=Files.readString(SOURCE);assertTrue(s.contains("showDestructiveConfirmation"));assertTrue(s.contains("access will be revoked"));assertTrue(s.contains("next authoritative validation"));assertTrue(s.contains("adminSessionManagement().orElseThrow().revoke(target.sessionId())"));assertTrue(s.contains("loading=false;load()"));}
 @Test void reasonVocabularyIsPresentedWithoutFreeText(){assertEquals("Revoked by an administrator",AdminSessionsPane.reason("ADMIN_REVOKED"));assertEquals("Account security change",AdminSessionsPane.reason("SECURITY"));assertEquals("Session ended",AdminSessionsPane.reason("FUTURE"));}
}
