package com.shale.server.controller;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.*;import java.util.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import com.shale.core.dto.*;import com.shale.core.model.*;import com.shale.core.service.ApplicationInstanceAdminReadServicePort;
import com.shale.server.auth.CurrentUserProfileService;import com.shale.server.dto.AuthenticatedUserResponse;import com.shale.server.runtime.*;import jakarta.servlet.http.HttpServletRequest;

class ApplicationInstanceAdminControllerTest {
	Recording service;MockMvc mvc;String token;boolean admin=true;
	@BeforeEach void setup(){service=new Recording();var ts=new ShaleAuthTokenService("test-auth-token-secret-that-is-long-enough",3600,Clock.systemUTC());token="Bearer "+ts.issue(new ServerPrincipal(31,7,"admin@test"));CurrentUserProfileService profiles=p->Optional.of(new AuthenticatedUserResponse(true,p.userId(),p.shaleClientId(),p.email(),"Admin User","Admin","User",admin,false,"AU","#000000"));mvc=MockMvcBuilders.standaloneSetup(new ApplicationInstanceAdminController(service,new ServerRuntimeSessionState(new BearerTokenServerSessionResolver(ts,new InMemoryTokenRevocationStore()),requests()),profiles)).setControllerAdvice(new ApiExceptionHandler()).build();}
	@Test void adminUsesPrincipalNotSpoofedTenantAndReceivesSafeNullPreservingPage()throws Exception{mvc.perform(get("/api/admin/application-instances?shaleClientId=8&size=1&activeOnly=true").header("Authorization",token)).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].applicationInstanceId").value(9)).andExpect(jsonPath("$.items[0].userEmail").value("user@test")).andExpect(jsonPath("$.items[0].machineId").value("12345678-1234-4234-8234-123456789abc")).andExpect(jsonPath("$.items[0].lastHeartbeatAt").doesNotExist()).andExpect(jsonPath("$.items[0].lastHumanActivityAt").doesNotExist()).andExpect(jsonPath("$.items[0].endedAt").doesNotExist()).andExpect(jsonPath("$.items[0].rowVer").doesNotExist()).andExpect(jsonPath("$.items[0].shaleClientId").doesNotExist()).andExpect(jsonPath("$.total").doesNotExist());Assertions.assertEquals(7,service.tenant);Assertions.assertEquals(31,service.actor);Assertions.assertTrue(service.filter.activeOnly());}
	@Test void ordinaryAndUnauthenticatedUsersAreDeniedWithoutQuerying()throws Exception{admin=false;mvc.perform(get("/api/admin/application-instances").header("Authorization",token)).andExpect(status().isForbidden());mvc.perform(get("/api/admin/application-instances")).andExpect(status().isUnauthorized());Assertions.assertEquals(0,service.calls);}
	@Test void filtersPaginationAndDistributionArePassedCanonically()throws Exception{mvc.perform(get("/api/admin/application-instances?page=2&size=100&clientType=DESKTOP&version=1.0.10&userId=22&since=2026-09-01T00:00:00Z").header("Authorization",token)).andExpect(status().isOk());Assertions.assertEquals(2,service.page);Assertions.assertEquals(100,service.size);Assertions.assertEquals(new SemanticVersion(1,0,10),service.filter.applicationVersion());Assertions.assertEquals(22,service.filter.userId());mvc.perform(get("/api/admin/application-instances/version-distribution").header("Authorization",token)).andExpect(status().isOk()).andExpect(jsonPath("$[0].applicationVersion").value("1.0.10")).andExpect(jsonPath("$[0].instanceCount").value(2)).andExpect(jsonPath("$[0].distinctUserCount").value(1));}
	@Test void malformedFiltersAreBadRequests()throws Exception{mvc.perform(get("/api/admin/application-instances?version=1.0.01").header("Authorization",token)).andExpect(status().isBadRequest());mvc.perform(get("/api/admin/application-instances?clientType=OTHER").header("Authorization",token)).andExpect(status().isBadRequest());mvc.perform(get("/api/admin/application-instances?since=yesterday").header("Authorization",token)).andExpect(status().isBadRequest());}
	static ObjectProvider<HttpServletRequest> requests(){return new ObjectProvider<>(){public HttpServletRequest getObject(Object...a){return getIfAvailable();}public HttpServletRequest getIfAvailable(){var a=org.springframework.web.context.request.RequestContextHolder.getRequestAttributes();return a instanceof org.springframework.web.context.request.ServletRequestAttributes s?s.getRequest():null;}public HttpServletRequest getIfUnique(){return getIfAvailable();}public HttpServletRequest getObject(){return getIfAvailable();}};}
	static final class Recording implements ApplicationInstanceAdminReadServicePort{int tenant,actor,page,size,calls;Filter filter;public ApplicationInstanceAdminPage listRecent(int t,int a,Filter f,int p,int s){calls++;tenant=t;actor=a;filter=f;page=p;size=s;var row=new AdminApplicationInstanceView(9,22,"User Name","user@test",UUID.fromString("12345678-1234-4234-8234-123456789abc"),ClientType.DESKTOP,new SemanticVersion(1,0,9),Instant.parse("2026-09-20T00:00:00Z"),null,null,null);return new ApplicationInstanceAdminPage(List.of(row),p,s);}public List<ApplicationVersionDistributionView> getVersionDistribution(int t,int a,Instant since){calls++;return List.of(new ApplicationVersionDistributionView(new SemanticVersion(1,0,10),2,1,Instant.parse("2026-09-20T01:00:00Z")),new ApplicationVersionDistributionView(new SemanticVersion(1,0,9),1,1,null));}}
}
