package com.shale.server.controller;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.*;import java.util.UUID;import org.junit.jupiter.api.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import com.shale.core.dto.ApplicationInstanceView;import com.shale.core.model.*;import com.shale.core.service.ApplicationInstanceServicePort;import com.shale.server.runtime.*;import jakarta.servlet.http.HttpServletRequest;
class ApplicationInstanceControllerTest{
	Recording service;MockMvc mvc;String token;UUID machine=UUID.fromString("12345678-1234-4234-8234-123456789abc");
	@BeforeEach void setup(){service=new Recording();var ts=new ShaleAuthTokenService("test-auth-token-secret-that-is-long-enough",3600,Clock.systemUTC());token="Bearer "+ts.issue(new ServerPrincipal(31,41,"a@test"));mvc=MockMvcBuilders.standaloneSetup(new ApplicationInstanceController(service,new ServerRuntimeSessionState(new BearerTokenServerSessionResolver(ts,new InMemoryTokenRevocationStore()),requests()))).setControllerAdvice(new ApiExceptionHandler()).build();}
	@Test void authenticatedEnrollmentUsesPrincipalAndStrictClientInput()throws Exception{mvc.perform(post("/api/application-instances").header("Authorization",token).contentType(MediaType.APPLICATION_JSON).content("{\"machineId\":\""+machine+"\",\"clientType\":\"DESKTOP\",\"applicationVersion\":\"1.0.130\",\"shaleClientId\":999,\"userId\":999}" )).andExpect(status().isOk()).andExpect(jsonPath("$.id").value(7)).andExpect(jsonPath("$.applicationVersion").value("1.0.130")).andExpect(jsonPath("$.endedAt").doesNotExist());Assertions.assertEquals(41,service.tenant);Assertions.assertEquals(31,service.user);}
	@Test void unauthenticatedAndMalformedEnrollmentAreRejected()throws Exception{mvc.perform(post("/api/application-instances").contentType(MediaType.APPLICATION_JSON).content("{\"machineId\":\""+machine+"\",\"clientType\":\"DESKTOP\",\"applicationVersion\":\"1.0.130\"}" )).andExpect(status().isUnauthorized());mvc.perform(post("/api/application-instances").header("Authorization",token).contentType(MediaType.APPLICATION_JSON).content("{\"machineId\":\"bad\",\"clientType\":\"WEB\",\"applicationVersion\":\"v1\"}" )).andExpect(status().isBadRequest());}
	@Test void ownerEndIsIdempotentAndUnknownIsSafe()throws Exception{mvc.perform(post("/api/application-instances/7/end").header("Authorization",token)).andExpect(status().isOk()).andExpect(jsonPath("$.endedAt").exists());mvc.perform(post("/api/application-instances/7/end").header("Authorization",token)).andExpect(status().isOk());mvc.perform(post("/api/application-instances/8/end").header("Authorization",token)).andExpect(status().isNotFound()).andExpect(jsonPath("$.message").value("Application instance was not found."));}
	@Test void authenticatedHeartbeatUsesPrincipalAcceptsNullAndReturnsOnlySafeState()throws Exception{mvc.perform(post("/api/application-instances/7/heartbeat").header("Authorization",token).contentType(MediaType.APPLICATION_JSON).content("{\"applicationVersion\":\"1.0.131\",\"lastHumanActivityAt\":null,\"shaleClientId\":999,\"userId\":999}" )).andExpect(status().isOk()).andExpect(jsonPath("$.lastHeartbeatAt").exists()).andExpect(jsonPath("$.applicationVersion").value("1.0.131")).andExpect(jsonPath("$.shaleClientId").doesNotExist()).andExpect(jsonPath("$.userId").doesNotExist()).andExpect(jsonPath("$.rowVer").doesNotExist());Assertions.assertEquals(41,service.tenant);Assertions.assertEquals(31,service.user);}
	@Test void heartbeatRejectsMalformedEndedUnknownAndUnauthenticated()throws Exception{mvc.perform(post("/api/application-instances/7/heartbeat").contentType(MediaType.APPLICATION_JSON).content("{\"applicationVersion\":\"1.0.130\"}")).andExpect(status().isUnauthorized());mvc.perform(post("/api/application-instances/7/heartbeat").header("Authorization",token).contentType(MediaType.APPLICATION_JSON).content("{\"applicationVersion\":\"v1\"}")).andExpect(status().isBadRequest());service.endedHeartbeat=true;mvc.perform(post("/api/application-instances/7/heartbeat").header("Authorization",token).contentType(MediaType.APPLICATION_JSON).content("{\"applicationVersion\":\"1.0.130\"}")).andExpect(status().isConflict());service.endedHeartbeat=false;mvc.perform(post("/api/application-instances/8/heartbeat").header("Authorization",token).contentType(MediaType.APPLICATION_JSON).content("{\"applicationVersion\":\"1.0.130\"}")).andExpect(status().isNotFound());}
	static ObjectProvider<HttpServletRequest> requests(){return new ObjectProvider<>(){public HttpServletRequest getObject(Object...a){return getIfAvailable();}public HttpServletRequest getIfAvailable(){var a=org.springframework.web.context.request.RequestContextHolder.getRequestAttributes();return a instanceof org.springframework.web.context.request.ServletRequestAttributes s?s.getRequest():null;}public HttpServletRequest getIfUnique(){return getIfAvailable();}public HttpServletRequest getObject(){return getIfAvailable();}};}
	final class Recording implements ApplicationInstanceServicePort{int tenant,user;Instant ended;boolean endedHeartbeat;public ApplicationInstanceView enroll(int t,int u,UUID m,ClientType c,SemanticVersion v){tenant=t;user=u;return new ApplicationInstanceView(7,m,c,v,Instant.parse("2026-09-28T00:00:00Z"),null);}public ApplicationInstanceView heartbeat(int t,int u,long id,SemanticVersion v,Instant a){tenant=t;user=u;if(id!=7)throw new SecurityException();if(endedHeartbeat)throw new com.shale.core.service.EndedApplicationInstanceException();return new ApplicationInstanceView(7,machine,ClientType.DESKTOP,v,Instant.parse("2026-09-28T00:00:00Z"),null,Instant.parse("2026-09-29T00:00:00Z"),a);}public ApplicationInstanceView end(int t,int u,long id){if(id!=7)throw new SecurityException();if(ended==null)ended=Instant.parse("2026-09-28T01:00:00Z");return new ApplicationInstanceView(7,machine,ClientType.DESKTOP,new SemanticVersion(1,0,130),Instant.parse("2026-09-28T00:00:00Z"),ended);}}
}
