package com.shale.core.update;

public enum UpdateFailureCode {
	UPDATER_LAUNCH_FAILED,
	MANIFEST_UNAVAILABLE,
	PACKAGE_UNAVAILABLE,
	PACKAGE_DOWNLOAD_FAILED,
	PACKAGE_VALIDATION_FAILED,
	PACKAGE_EXTRACTION_FAILED,
	INSTALL_APPLY_FAILED
}
