/* Phase 6B catalog verifier. Every FindingCount must be zero. */
SELECT 'TableExists' CheckName,CASE WHEN OBJECT_ID(N'dbo.AdministrativeReadAuditLog',N'U') IS NULL THEN 1 ELSE 0 END FindingCount;
SELECT 'ExactColumns' CheckName,ABS(7-COUNT(*))+SUM(CASE WHEN (name='Id' AND system_type_id=127 AND is_nullable=0) OR (name='ShaleClientId' AND system_type_id=56 AND is_nullable=0) OR (name='ActorUserId' AND system_type_id=56 AND is_nullable=0) OR (name='ReadType' AND system_type_id=167 AND max_length=64 AND is_nullable=0) OR (name='OccurredAt' AND system_type_id=42 AND scale=7 AND is_nullable=0) OR (name='ResultCount' AND system_type_id=56 AND is_nullable=0) OR (name='Metadata' AND system_type_id=167 AND max_length=1000 AND is_nullable=1) THEN 0 ELSE 1 END) FindingCount FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog');
SELECT 'PrimaryKey' CheckName,CASE WHEN EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND type='PK' AND name=N'PK_AdministrativeReadAuditLog') THEN 0 ELSE 1 END FindingCount;
SELECT 'TrustedForeignKeys' CheckName,COUNT(*) FindingCount FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND (is_disabled=1 OR is_not_trusted=1 OR name NOT IN(N'FK_AdministrativeReadAuditLog_Client',N'FK_AdministrativeReadAuditLog_ActorTenant'));
SELECT 'ExpectedForeignKeyCount' CheckName,CASE WHEN COUNT(*)=2 THEN 0 ELSE 1 END FindingCount FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog');
SELECT 'ClosedReadTypes' CheckName,CASE WHEN EXISTS(SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND name=N'CK_AdministrativeReadAuditLog_ReadType' AND definition LIKE '%APPLICATION_INSTANCE_RECENT_LIST%' AND definition LIKE '%APPLICATION_INSTANCE_VERSION_DISTRIBUTION%') THEN 0 ELSE 1 END FindingCount;
SELECT 'ServerUtcDefault' CheckName,CASE WHEN EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND name=N'DF_AdministrativeReadAuditLog_OccurredAt' AND definition LIKE '%sysutcdatetime%') THEN 0 ELSE 1 END FindingCount;
SELECT 'MetadataBoundAndResultCheck' CheckName,(CASE WHEN COL_LENGTH(N'dbo.AdministrativeReadAuditLog',N'Metadata')=1000 THEN 0 ELSE 1 END)+(CASE WHEN EXISTS(SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND name=N'CK_AdministrativeReadAuditLog_ResultCount') THEN 0 ELSE 1 END) FindingCount;
SELECT 'ExpectedIndex' CheckName,CASE WHEN EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND name=N'IX_AdministrativeReadAuditLog_TenantOccurred') THEN 0 ELSE 1 END FindingCount;
SELECT 'StrictRlsPredicates' CheckName,CASE WHEN (SELECT COUNT(*) FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND predicate_definition LIKE '%fn_FilterByTenant%' AND predicate_definition NOT LIKE '%OrGlobal%')=3 THEN 0 ELSE 1 END FindingCount;
SELECT 'NoOverlayPredicate' CheckName,COUNT(*) FindingCount FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.AdministrativeReadAuditLog') AND predicate_definition LIKE '%OrGlobal%';
SELECT 'NoSeedRows' CheckName,COUNT(*) FindingCount FROM dbo.AdministrativeReadAuditLog;
SELECT 'PriorPhaseTableIntact' CheckName,CASE WHEN OBJECT_ID(N'dbo.ApplicationInstances',N'U') IS NULL THEN 1 ELSE 0 END FindingCount;
