/* Contacts Phase 1A read-only verification: counts and metadata only; no Contact PHI is selected.
   Run only through the approved all-tenant migration/administrative connection, never shale_app or
   shale_runtime. NULL session context is mandatory even when the principal can bypass RLS. */
SET NOCOUNT ON;
/* Operator must set this to 1 only after independently confirming this database principal sees all tenants. */
DECLARE @OperatorVerifiedAllTenantVisibility bit=0;
IF SESSION_CONTEXT(N'ShaleClientId') IS NOT NULL
 THROW 56200, 'Verification requires SESSION_CONTEXT(N''ShaleClientId'') to be NULL; reconnect rather than clearing retained application context.',1;
IF USER_NAME() IN(N'shale_app',N'shale_runtime') OR (ISNULL(IS_SRVROLEMEMBER(N'sysadmin'),0)<>1 AND ISNULL(IS_MEMBER(N'db_owner'),0)<>1)
 THROW 56201, 'Use the approved all-tenant migration/administrative database principal, not an application connection.',1;
IF @OperatorVerifiedAllTenantVisibility<>1
 THROW 56202, 'Operator-verified all-tenant visibility is required; set the acknowledgement only after independent visibility preflight.',1;

/* Exact column contract, including byte lengths, nullability, identity, and rowversion. */
DECLARE @Columns TABLE(TableName sysname,ColumnName sysname,TypeName sysname,MaxLength smallint,Nullable bit,IdentityColumn bit,RowVersionColumn bit);
INSERT @Columns VALUES
(N'ContactTypes',N'Id',N'int',4,0,1,0),(N'ContactTypes',N'ShaleClientId',N'int',4,1,0,0),(N'ContactTypes',N'SystemKey',N'nvarchar',128,0,0,0),(N'ContactTypes',N'Name',N'nvarchar',200,0,0,0),(N'ContactTypes',N'Description',N'nvarchar',1000,1,0,0),(N'ContactTypes',N'SortOrder',N'int',4,0,0,0),(N'ContactTypes',N'IsActive',N'bit',1,0,0,0),(N'ContactTypes',N'IsDeleted',N'bit',1,0,0,0),(N'ContactTypes',N'DeletedAt',N'datetime2',8,1,0,0),(N'ContactTypes',N'DeletedByUserId',N'int',4,1,0,0),(N'ContactTypes',N'CreatedAt',N'datetime2',8,0,0,0),(N'ContactTypes',N'CreatedByUserId',N'int',4,1,0,0),(N'ContactTypes',N'UpdatedAt',N'datetime2',8,1,0,0),(N'ContactTypes',N'UpdatedByUserId',N'int',4,1,0,0),(N'ContactTypes',N'RowVer',N'timestamp',8,0,0,1),
(N'Specialties',N'Id',N'int',4,0,1,0),(N'Specialties',N'ShaleClientId',N'int',4,1,0,0),(N'Specialties',N'SystemKey',N'nvarchar',128,0,0,0),(N'Specialties',N'Name',N'nvarchar',200,0,0,0),(N'Specialties',N'Description',N'nvarchar',1000,1,0,0),(N'Specialties',N'SortOrder',N'int',4,0,0,0),(N'Specialties',N'IsActive',N'bit',1,0,0,0),(N'Specialties',N'IsDeleted',N'bit',1,0,0,0),(N'Specialties',N'DeletedAt',N'datetime2',8,1,0,0),(N'Specialties',N'DeletedByUserId',N'int',4,1,0,0),(N'Specialties',N'CreatedAt',N'datetime2',8,0,0,0),(N'Specialties',N'CreatedByUserId',N'int',4,1,0,0),(N'Specialties',N'UpdatedAt',N'datetime2',8,1,0,0),(N'Specialties',N'UpdatedByUserId',N'int',4,1,0,0),(N'Specialties',N'RowVer',N'timestamp',8,0,0,1),
(N'CredentialDefinitions',N'Id',N'int',4,0,1,0),(N'CredentialDefinitions',N'ShaleClientId',N'int',4,1,0,0),(N'CredentialDefinitions',N'SystemKey',N'nvarchar',128,0,0,0),(N'CredentialDefinitions',N'Name',N'nvarchar',200,0,0,0),(N'CredentialDefinitions',N'Abbreviation',N'nvarchar',100,0,0,0),(N'CredentialDefinitions',N'Description',N'nvarchar',1000,1,0,0),(N'CredentialDefinitions',N'SortOrder',N'int',4,0,0,0),(N'CredentialDefinitions',N'IsActive',N'bit',1,0,0,0),(N'CredentialDefinitions',N'IsDeleted',N'bit',1,0,0,0),(N'CredentialDefinitions',N'DeletedAt',N'datetime2',8,1,0,0),(N'CredentialDefinitions',N'DeletedByUserId',N'int',4,1,0,0),(N'CredentialDefinitions',N'CreatedAt',N'datetime2',8,0,0,0),(N'CredentialDefinitions',N'CreatedByUserId',N'int',4,1,0,0),(N'CredentialDefinitions',N'UpdatedAt',N'datetime2',8,1,0,0),(N'CredentialDefinitions',N'UpdatedByUserId',N'int',4,1,0,0),(N'CredentialDefinitions',N'RowVer',N'timestamp',8,0,0,1);
INSERT @Columns SELECT t,c,ty,l,n,i,r FROM (VALUES
(N'ContactContactTypes',N'Id',N'bigint',8,0,1,0),(N'ContactContactTypes',N'ShaleClientId',N'int',4,0,0,0),(N'ContactContactTypes',N'ContactId',N'int',4,0,0,0),(N'ContactContactTypes',N'ContactTypeId',N'int',4,0,0,0),
(N'ContactSpecialties',N'Id',N'bigint',8,0,1,0),(N'ContactSpecialties',N'ShaleClientId',N'int',4,0,0,0),(N'ContactSpecialties',N'ContactId',N'int',4,0,0,0),(N'ContactSpecialties',N'SpecialtyId',N'int',4,0,0,0),
(N'ContactCredentials',N'Id',N'bigint',8,0,1,0),(N'ContactCredentials',N'ShaleClientId',N'int',4,0,0,0),(N'ContactCredentials',N'ContactId',N'int',4,0,0,0),(N'ContactCredentials',N'CredentialDefinitionId',N'int',4,0,0,0),(N'ContactCredentials',N'DisplayOrder',N'int',4,0,0,0))v(t,c,ty,l,n,i,r);
INSERT @Columns SELECT t,c,ty,l,n,i,r FROM (SELECT t,v.* FROM (VALUES(N'ContactContactTypes'),(N'ContactSpecialties'),(N'ContactCredentials'))q(t) CROSS APPLY(VALUES(N'IsDeleted',N'bit',1,0,0,0),(N'CreatedAt',N'datetime2',8,0,0,0),(N'CreatedByUserId',N'int',4,1,0,0),(N'UpdatedAt',N'datetime2',8,1,0,0),(N'UpdatedByUserId',N'int',4,1,0,0),(N'DeletedAt',N'datetime2',8,1,0,0),(N'DeletedByUserId',N'int',4,1,0,0),(N'RowVer',N'timestamp',8,0,0,1))v(c,ty,l,n,i,r))x;
SELECT N'column contract mismatches (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM @Columns e LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.'+e.TableName) AND c.name=e.ColumnName LEFT JOIN sys.types y ON y.user_type_id=c.user_type_id WHERE c.column_id IS NULL OR y.name<>e.TypeName OR c.max_length<>e.MaxLength OR c.is_nullable<>e.Nullable OR c.is_identity<>e.IdentityColumn OR (CASE WHEN c.system_type_id=189 THEN 1 ELSE 0 END)<>e.RowVersionColumn;
SELECT N'additional non-Phase-1A columns (allowed; informational)' CheckName,COUNT_BIG(*) FindingCount FROM sys.columns c JOIN sys.tables t ON t.object_id=c.object_id WHERE t.name IN(N'ContactTypes',N'Specialties',N'CredentialDefinitions',N'ContactContactTypes',N'ContactSpecialties',N'ContactCredentials') AND NOT EXISTS(SELECT 1 FROM @Columns e WHERE e.TableName=t.name AND e.ColumnName=c.name);
SELECT N'structured Contact column contract mismatches (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM (VALUES(N'Prefix',100),(N'MiddleName',200),(N'PreferredName',200),(N'Suffix',100))e(c,l) LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.Contacts') AND c.name=e.c WHERE c.column_id IS NULL OR c.system_type_id<>231 OR c.max_length<>e.l OR c.is_nullable<>1;

/* Defaults and CHECK definitions are emitted without row data for manual contract comparison. */
SELECT N'critical defaults missing/incompatible (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM (VALUES(N'ContactTypes',N'SortOrder',N'((0))'),(N'ContactTypes',N'IsActive',N'((1))'),(N'ContactTypes',N'IsDeleted',N'((0))'),(N'ContactTypes',N'CreatedAt',N'(sysutcdatetime())'),(N'Specialties',N'SortOrder',N'((0))'),(N'Specialties',N'IsActive',N'((1))'),(N'Specialties',N'IsDeleted',N'((0))'),(N'Specialties',N'CreatedAt',N'(sysutcdatetime())'),(N'CredentialDefinitions',N'SortOrder',N'((0))'),(N'CredentialDefinitions',N'IsActive',N'((1))'),(N'CredentialDefinitions',N'IsDeleted',N'((0))'),(N'CredentialDefinitions',N'CreatedAt',N'(sysutcdatetime())'),(N'ContactContactTypes',N'IsDeleted',N'((0))'),(N'ContactContactTypes',N'CreatedAt',N'(sysutcdatetime())'),(N'ContactSpecialties',N'IsDeleted',N'((0))'),(N'ContactSpecialties',N'CreatedAt',N'(sysutcdatetime())'),(N'ContactCredentials',N'IsDeleted',N'((0))'),(N'ContactCredentials',N'CreatedAt',N'(sysutcdatetime())'),(N'ContactCredentials',N'DisplayOrder',N'((0))'))e(t,c,d) LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.'+e.t) AND c.name=e.c LEFT JOIN sys.default_constraints dc ON dc.object_id=c.default_object_id WHERE dc.object_id IS NULL OR LOWER(REPLACE(dc.definition,N' ',N''))<>LOWER(e.d);
SELECT OBJECT_NAME(parent_object_id) TableName,name,definition,is_disabled,is_not_trusted FROM sys.check_constraints WHERE parent_object_id IN(OBJECT_ID(N'dbo.ContactTypes'),OBJECT_ID(N'dbo.Specialties'),OBJECT_ID(N'dbo.CredentialDefinitions'),OBJECT_ID(N'dbo.ContactContactTypes'),OBJECT_ID(N'dbo.ContactSpecialties'),OBJECT_ID(N'dbo.ContactCredentials')) ORDER BY 1,2;
SELECT N'definition lifecycle violations (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(SELECT Id FROM dbo.ContactTypes WHERE (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (IsActive<>0 OR DeletedAt IS NULL OR DeletedByUserId IS NULL)) UNION ALL SELECT Id FROM dbo.Specialties WHERE (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (IsActive<>0 OR DeletedAt IS NULL OR DeletedByUserId IS NULL)) UNION ALL SELECT Id FROM dbo.CredentialDefinitions WHERE (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (IsActive<>0 OR DeletedAt IS NULL OR DeletedByUserId IS NULL)))x;
SELECT N'assignment lifecycle violations (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(SELECT Id FROM dbo.ContactContactTypes WHERE (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (DeletedAt IS NULL OR DeletedByUserId IS NULL)) UNION ALL SELECT Id FROM dbo.ContactSpecialties WHERE (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (DeletedAt IS NULL OR DeletedByUserId IS NULL)) UNION ALL SELECT Id FROM dbo.ContactCredentials WHERE (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (DeletedAt IS NULL OR DeletedByUserId IS NULL)))x;
SELECT N'negative credential display order (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.ContactCredentials WHERE DisplayOrder<0;

/* Exact ordered key/include lists and normalized filters; compare every row to architecture contract. */
SELECT OBJECT_NAME(i.object_id) TableName,i.name IndexName,i.is_unique,i.is_primary_key,i.is_unique_constraint,i.has_filter,i.filter_definition,
 STRING_AGG(CASE WHEN ic.is_included_column=0 THEN c.name END,N',') WITHIN GROUP(ORDER BY ic.index_column_id) KeyColumns,
 STRING_AGG(CASE WHEN ic.is_included_column=1 THEN c.name END,N',') WITHIN GROUP(ORDER BY ic.index_column_id) IncludedColumns
FROM sys.indexes i JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id
WHERE i.object_id IN(OBJECT_ID(N'dbo.Contacts'),OBJECT_ID(N'dbo.ContactTypes'),OBJECT_ID(N'dbo.Specialties'),OBJECT_ID(N'dbo.CredentialDefinitions'),OBJECT_ID(N'dbo.ContactContactTypes'),OBJECT_ID(N'dbo.ContactSpecialties'),OBJECT_ID(N'dbo.ContactCredentials')) AND i.name IS NOT NULL GROUP BY i.object_id,i.name,i.is_unique,i.is_primary_key,i.is_unique_constraint,i.has_filter,i.filter_definition ORDER BY 1,2;
SELECT OBJECT_NAME(f.parent_object_id) ChildTable,f.name,STRING_AGG(pc.name,N',') WITHIN GROUP(ORDER BY fc.constraint_column_id) ChildColumns,OBJECT_NAME(f.referenced_object_id) ParentTable,STRING_AGG(rc.name,N',') WITHIN GROUP(ORDER BY fc.constraint_column_id) ParentColumns,f.is_disabled,f.is_not_trusted
FROM sys.foreign_keys f JOIN sys.foreign_key_columns fc ON fc.constraint_object_id=f.object_id JOIN sys.columns pc ON pc.object_id=fc.parent_object_id AND pc.column_id=fc.parent_column_id JOIN sys.columns rc ON rc.object_id=fc.referenced_object_id AND rc.column_id=fc.referenced_column_id WHERE f.parent_object_id IN(OBJECT_ID(N'dbo.ContactTypes'),OBJECT_ID(N'dbo.Specialties'),OBJECT_ID(N'dbo.CredentialDefinitions'),OBJECT_ID(N'dbo.ContactContactTypes'),OBJECT_ID(N'dbo.ContactSpecialties'),OBJECT_ID(N'dbo.ContactCredentials')) GROUP BY f.parent_object_id,f.name,f.referenced_object_id,f.is_disabled,f.is_not_trusted ORDER BY 1,2;
SELECT N'actor FK mapping mismatches (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM (SELECT t.t,a.a,N'FK_'+t.t+N'_'+a.a n FROM (VALUES(N'ContactTypes'),(N'Specialties'),(N'CredentialDefinitions'),(N'ContactContactTypes'),(N'ContactSpecialties'),(N'ContactCredentials'))t(t) CROSS JOIN(VALUES(N'CreatedByUserId'),(N'UpdatedByUserId'),(N'DeletedByUserId'))a(a))e LEFT JOIN sys.foreign_keys f ON f.parent_object_id=OBJECT_ID(N'dbo.'+e.t) AND f.name=e.n LEFT JOIN sys.foreign_key_columns fc ON fc.constraint_object_id=f.object_id WHERE f.object_id IS NULL OR f.referenced_object_id<>OBJECT_ID(N'dbo.Users') OR COL_NAME(fc.parent_object_id,fc.parent_column_id)<>e.a OR COL_NAME(fc.referenced_object_id,fc.referenced_column_id)<>N'id';

/* Contacts preflight and non-PHI population/invariant counts. */
SELECT N'Contacts Id int identity primary-key contract mismatches (expect 0)' CheckName,CASE WHEN EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.Contacts') AND name=N'Id' AND system_type_id=56 AND is_nullable=0 AND is_identity=1) AND EXISTS(SELECT 1 FROM sys.indexes i JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.key_ordinal=1 WHERE i.object_id=OBJECT_ID(N'dbo.Contacts') AND i.is_primary_key=1 AND COL_NAME(ic.object_id,ic.column_id)=N'Id') THEN 0 ELSE 1 END FindingCount;
SELECT N'Contacts ShaleClientId int NOT NULL contract mismatches (expect 0)' CheckName,CASE WHEN EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.Contacts') AND name=N'ShaleClientId' AND system_type_id=56 AND is_nullable=0) THEN 0 ELSE 1 END FindingCount;
SELECT N'Contacts with invalid/missing ShaleClient tenant (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.Contacts c LEFT JOIN dbo.ShaleClients sc ON sc.Id=c.ShaleClientId WHERE sc.Id IS NULL;
SELECT N'duplicate Contacts composite keys (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(SELECT 1 x FROM dbo.Contacts GROUP BY ShaleClientId,Id HAVING COUNT_BIG(*)>1)d;
SELECT N'global Expert definitions (expect exactly 1 after migration)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.ContactTypes WHERE ShaleClientId IS NULL AND SystemKey=N'expert';
SELECT N'incompatible global Expert definitions (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.ContactTypes WHERE ShaleClientId IS NULL AND SystemKey=N'expert' AND (Name<>N'Expert' OR IsActive<>1 OR IsDeleted<>0 OR DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL);
SELECT N'legacy IsExpert=1 Contacts (live baseline observed 0)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.Contacts WHERE IsExpert=1;
SELECT N'missing active Expert assignments (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.Contacts c WHERE c.IsExpert=1 AND NOT EXISTS(SELECT 1 FROM dbo.ContactContactTypes a JOIN dbo.ContactTypes d ON d.Id=a.ContactTypeId WHERE a.ShaleClientId=c.ShaleClientId AND a.ContactId=c.Id AND a.IsDeleted=0 AND d.ShaleClientId IS NULL AND d.SystemKey=N'expert');
SELECT N'active Expert assignments (live baseline currently expected 0)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.ContactContactTypes a JOIN dbo.ContactTypes d ON d.Id=a.ContactTypeId WHERE a.IsDeleted=0 AND d.ShaleClientId IS NULL AND d.SystemKey=N'expert';
SELECT N'duplicate active Expert assignments (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(SELECT a.ShaleClientId,a.ContactId FROM dbo.ContactContactTypes a JOIN dbo.ContactTypes d ON d.Id=a.ContactTypeId WHERE a.IsDeleted=0 AND d.ShaleClientId IS NULL AND d.SystemKey=N'expert' GROUP BY a.ShaleClientId,a.ContactId HAVING COUNT_BIG(*)>1)x;
SELECT N'duplicate active assignments (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(SELECT 1 x FROM dbo.ContactContactTypes WHERE IsDeleted=0 GROUP BY ShaleClientId,ContactId,ContactTypeId HAVING COUNT_BIG(*)>1 UNION ALL SELECT 1 FROM dbo.ContactSpecialties WHERE IsDeleted=0 GROUP BY ShaleClientId,ContactId,SpecialtyId HAVING COUNT_BIG(*)>1 UNION ALL SELECT 1 FROM dbo.ContactCredentials WHERE IsDeleted=0 GROUP BY ShaleClientId,ContactId,CredentialDefinitionId HAVING COUNT_BIG(*)>1)x;
SELECT N'cross-tenant Contact assignments (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(SELECT a.Id FROM dbo.ContactContactTypes a JOIN dbo.Contacts c ON c.Id=a.ContactId WHERE c.ShaleClientId<>a.ShaleClientId UNION ALL SELECT a.Id FROM dbo.ContactSpecialties a JOIN dbo.Contacts c ON c.Id=a.ContactId WHERE c.ShaleClientId<>a.ShaleClientId UNION ALL SELECT a.Id FROM dbo.ContactCredentials a JOIN dbo.Contacts c ON c.Id=a.ContactId WHERE c.ShaleClientId<>a.ShaleClientId)x;
SELECT N'cross-tenant definition assignments (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(SELECT a.Id FROM dbo.ContactContactTypes a JOIN dbo.ContactTypes d ON d.Id=a.ContactTypeId WHERE d.ShaleClientId IS NOT NULL AND d.ShaleClientId<>a.ShaleClientId UNION ALL SELECT a.Id FROM dbo.ContactSpecialties a JOIN dbo.Specialties d ON d.Id=a.SpecialtyId WHERE d.ShaleClientId IS NOT NULL AND d.ShaleClientId<>a.ShaleClientId UNION ALL SELECT a.Id FROM dbo.ContactCredentials a JOIN dbo.CredentialDefinitions d ON d.Id=a.CredentialDefinitionId WHERE d.ShaleClientId IS NOT NULL AND d.ShaleClientId<>a.ShaleClientId)x;

/* Exactly six expected FILTER predicates, all on the one enabled TenantFilter policy. No BLOCK convention is introduced. */
DECLARE @ExpectedRls TABLE(TableName sysname,FunctionName sysname); INSERT @ExpectedRls VALUES(N'ContactTypes',N'fn_FilterByTenantOrGlobal'),(N'Specialties',N'fn_FilterByTenantOrGlobal'),(N'CredentialDefinitions',N'fn_FilterByTenantOrGlobal'),(N'ContactContactTypes',N'fn_FilterByTenant'),(N'ContactSpecialties',N'fn_FilterByTenant'),(N'ContactCredentials',N'fn_FilterByTenant');
SELECT N'enabled TenantFilter policies (expect exactly 1)' CheckName,COUNT_BIG(*) FindingCount FROM sys.security_policies WHERE name=N'TenantFilter' AND is_enabled=1;
SELECT N'missing/wrong expected Phase 1A RLS predicates (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM @ExpectedRls e WHERE NOT EXISTS(SELECT 1 FROM sys.security_predicates sp JOIN sys.security_policies p ON p.object_id=sp.object_id WHERE p.name=N'TenantFilter' AND p.is_enabled=1 AND sp.target_object_id=OBJECT_ID(N'dbo.'+e.TableName) AND sp.predicate_type_desc=N'FILTER' AND OBJECT_SCHEMA_NAME(sp.predicate_object_id)=N'sec' AND OBJECT_NAME(sp.predicate_object_id)=e.FunctionName AND sp.predicate_definition LIKE N'%([ShaleClientId])%');
SELECT N'unexpected Phase 1A RLS predicates (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM sys.security_predicates sp WHERE sp.target_object_id IN(SELECT OBJECT_ID(N'dbo.'+TableName) FROM @ExpectedRls) AND NOT EXISTS(SELECT 1 FROM @ExpectedRls e JOIN sys.security_policies p ON p.name=N'TenantFilter' AND p.is_enabled=1 WHERE sp.object_id=p.object_id AND sp.target_object_id=OBJECT_ID(N'dbo.'+e.TableName) AND sp.predicate_type_desc=N'FILTER' AND OBJECT_SCHEMA_NAME(sp.predicate_object_id)=N'sec' AND OBJECT_NAME(sp.predicate_object_id)=e.FunctionName AND sp.predicate_definition LIKE N'%([ShaleClientId])%');
SELECT N'dbo.Contacts TenantFilter predicates (existing condition; expect 0 in Phase 1A)' CheckName,COUNT_BIG(*) FindingCount FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.Contacts');

/* Named contract inventory: the detailed result sets above must show these exact semantic objects. */
SELECT N'required named indexes missing (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM(VALUES
(N'Contacts',N'UX_Contacts_ShaleClientId_Id'),(N'ContactTypes',N'PK_ContactTypes'),(N'ContactTypes',N'UX_ContactTypes_Global_SystemKey'),(N'ContactTypes',N'UX_ContactTypes_Tenant_SystemKey'),
(N'Specialties',N'PK_Specialties'),(N'Specialties',N'UX_Specialties_Global_SystemKey'),(N'Specialties',N'UX_Specialties_Tenant_SystemKey'),(N'CredentialDefinitions',N'PK_CredentialDefinitions'),(N'CredentialDefinitions',N'UX_CredentialDefinitions_Global_SystemKey'),(N'CredentialDefinitions',N'UX_CredentialDefinitions_Tenant_SystemKey'),
(N'ContactContactTypes',N'PK_ContactContactTypes'),(N'ContactContactTypes',N'UX_ContactContactTypes_Active'),(N'ContactSpecialties',N'PK_ContactSpecialties'),(N'ContactSpecialties',N'UX_ContactSpecialties_Active'),(N'ContactCredentials',N'PK_ContactCredentials'),(N'ContactCredentials',N'UX_ContactCredentials_Active'),(N'ContactCredentials',N'IX_ContactCredentials_Display'))e(t,n)
WHERE NOT EXISTS(SELECT 1 FROM sys.indexes i WHERE i.object_id=OBJECT_ID(N'dbo.'+e.t) AND i.name=e.n);
SELECT N'Contacts composite unique key semantic mismatches (expect 0)' CheckName,COUNT_BIG(*) FindingCount FROM sys.indexes i OUTER APPLY(SELECT STRING_AGG(c.name,N',') WITHIN GROUP(ORDER BY ic.index_column_id) keys,COUNT(CASE WHEN ic.is_included_column=1 THEN 1 END) includes FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id)x WHERE i.object_id=OBJECT_ID(N'dbo.Contacts') AND i.name=N'UX_Contacts_ShaleClientId_Id' AND (i.is_unique<>1 OR i.has_filter<>0 OR x.keys<>N'ShaleClientId,Id' OR x.includes<>0);
