/* Read-only Organizations Phase 1A verification. It changes no application table or RLS state. */
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
DECLARE @OperatorVerifiedAllTenantVisibility bit=0;
IF SESSION_CONTEXT(N'ShaleClientId') IS NOT NULL THROW 57100,'Verification requires NULL SESSION_CONTEXT(ShaleClientId).',1;
IF USER_NAME() IN(N'shale_app',N'shale_runtime') OR (ISNULL(IS_SRVROLEMEMBER(N'sysadmin'),0)<>1 AND ISNULL(IS_MEMBER(N'db_owner'),0)<>1) THROW 57101,'Use an approved all-tenant administrative principal.',1;
IF @OperatorVerifiedAllTenantVisibility<>1 THROW 57102,'Acknowledge independently verified all-tenant visibility before verification.',1;
IF OBJECT_ID(N'dbo.OrganizationTypes',N'U') IS NULL OR OBJECT_ID(N'dbo.Organizations',N'U') IS NULL OR OBJECT_ID(N'dbo.OrganizationOrganizationTypes',N'U') IS NULL THROW 57103,'Required Phase 1A table is missing.',1;

DECLARE @Findings TABLE(CheckName nvarchar(200),FindingCount bigint);
/* Exact required column contract; additional columns from later additive phases are allowed. */
INSERT @Findings SELECT N'OrganizationTypes column contract mismatches',COUNT_BIG(*) FROM (VALUES
(N'OrganizationTypeId',N'int',4,0,1,0),(N'Name',N'nvarchar',200,0,0,0),(N'ShaleClientId',N'int',4,1,0,0),(N'SystemKey',N'nvarchar',128,0,0,0),(N'Description',N'nvarchar',1000,1,0,0),(N'Color',N'nvarchar',40,0,0,0),(N'SortOrder',N'int',4,0,0,0),(N'IsActive',N'bit',1,0,0,0),(N'IsDeleted',N'bit',1,0,0,0),(N'CreatedAt',N'datetime2',8,0,0,0),(N'CreatedByUserId',N'int',4,1,0,0),(N'UpdatedAt',N'datetime2',8,1,0,0),(N'UpdatedByUserId',N'int',4,1,0,0),(N'DeletedAt',N'datetime2',8,1,0,0),(N'DeletedByUserId',N'int',4,1,0,0),(N'RowVer',N'timestamp',8,0,0,1))e(n,t,l,z,i,r)
LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.OrganizationTypes') AND c.name=e.n LEFT JOIN sys.types y ON y.user_type_id=c.user_type_id WHERE c.column_id IS NULL OR y.name<>e.t OR c.max_length<>e.l OR c.is_nullable<>e.z OR c.is_identity<>e.i OR (CASE WHEN c.system_type_id=189 THEN 1 ELSE 0 END)<>e.r;
INSERT @Findings SELECT N'assignment column contract mismatches',COUNT_BIG(*) FROM (VALUES
(N'Id',N'bigint',8,0,1,0),(N'ShaleClientId',N'int',4,0,0,0),(N'OrganizationId',N'int',4,0,0,0),(N'OrganizationTypeId',N'int',4,0,0,0),(N'IsPrimary',N'bit',1,0,0,0),(N'SortOrder',N'int',4,0,0,0),(N'IsDeleted',N'bit',1,0,0,0),(N'CreatedAt',N'datetime2',8,0,0,0),(N'CreatedByUserId',N'int',4,1,0,0),(N'UpdatedAt',N'datetime2',8,1,0,0),(N'UpdatedByUserId',N'int',4,1,0,0),(N'DeletedAt',N'datetime2',8,1,0,0),(N'DeletedByUserId',N'int',4,1,0,0),(N'RowVer',N'timestamp',8,0,0,1))e(n,t,l,z,i,r)
LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.OrganizationOrganizationTypes') AND c.name=e.n LEFT JOIN sys.types y ON y.user_type_id=c.user_type_id WHERE c.column_id IS NULL OR y.name<>e.t OR c.max_length<>e.l OR c.is_nullable<>e.z OR c.is_identity<>e.i OR (CASE WHEN c.system_type_id=189 THEN 1 ELSE 0 END)<>e.r;
INSERT @Findings SELECT N'datetime2 precision/scale mismatches',COUNT_BIG(*) FROM sys.columns WHERE object_id IN(OBJECT_ID(N'dbo.OrganizationTypes'),OBJECT_ID(N'dbo.OrganizationOrganizationTypes')) AND name IN(N'CreatedAt',N'UpdatedAt',N'DeletedAt') AND (precision<>27 OR scale<>7);
INSERT @Findings SELECT N'ShaleClientId defaults still present',COUNT_BIG(*) FROM sys.columns c JOIN sys.default_constraints d ON d.object_id=c.default_object_id WHERE c.object_id=OBJECT_ID(N'dbo.OrganizationTypes') AND c.name=N'ShaleClientId';
INSERT @Findings SELECT N'critical default mismatches',COUNT_BIG(*) FROM (VALUES(N'OrganizationTypes',N'SortOrder',N'((0))'),(N'OrganizationTypes',N'IsActive',N'((1))'),(N'OrganizationTypes',N'IsDeleted',N'((0))'),(N'OrganizationTypes',N'CreatedAt',N'(sysutcdatetime())'),(N'OrganizationTypes',N'Color',N'(n''#6c757d'')'),(N'OrganizationOrganizationTypes',N'IsPrimary',N'((0))'),(N'OrganizationOrganizationTypes',N'SortOrder',N'((0))'),(N'OrganizationOrganizationTypes',N'IsDeleted',N'((0))'),(N'OrganizationOrganizationTypes',N'CreatedAt',N'(sysutcdatetime())'))e(t,c,d) LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.'+e.t) AND c.name=e.c LEFT JOIN sys.default_constraints dc ON dc.object_id=c.default_object_id WHERE dc.object_id IS NULL OR LOWER(REPLACE(dc.definition,N' ',N''))<>e.d;

INSERT @Findings SELECT N'unexpected mutation of baseline OrganizationTypes',COUNT_BIG(*) FROM (VALUES(1,N'Provider',7,N'provider',N'#0F766E',0),(2,N'Facility',7,N'facility',N'#2563EB',1),(3,N'Firm',7,N'firm',N'#7C3AED',2),(4,N'Agency',7,N'agency',N'#D97706',3),(5,N'Insurer',7,N'insurer',N'#059669',4),(6,N'Lab',7,N'lab',N'#0891B2',5),(7,N'Other',7,N'other',N'#6B7280',6))e(Id,Name,Tenant,SystemKey,Color,SortOrder) LEFT JOIN dbo.OrganizationTypes d ON d.OrganizationTypeId=e.Id WHERE d.OrganizationTypeId IS NULL OR d.Name<>e.Name OR d.ShaleClientId<>e.Tenant OR d.SystemKey<>e.SystemKey OR d.Color<>e.Color OR d.SortOrder<>e.SortOrder;
INSERT @Findings SELECT N'invalid SystemKeys',COUNT_BIG(*) FROM dbo.OrganizationTypes WHERE SystemKey<>LOWER(SystemKey) OR NULLIF(LTRIM(RTRIM(SystemKey)),N'') IS NULL OR SystemKey LIKE N'%[^a-z0-9_]%' OR LEFT(SystemKey,1) NOT LIKE N'[a-z]';
INSERT @Findings SELECT N'duplicate global SystemKeys',COUNT_BIG(*) FROM(SELECT SystemKey FROM dbo.OrganizationTypes WHERE ShaleClientId IS NULL GROUP BY SystemKey HAVING COUNT_BIG(*)>1)x;
INSERT @Findings SELECT N'duplicate tenant SystemKeys',COUNT_BIG(*) FROM(SELECT ShaleClientId,SystemKey FROM dbo.OrganizationTypes WHERE ShaleClientId IS NOT NULL GROUP BY ShaleClientId,SystemKey HAVING COUNT_BIG(*)>1)x;
INSERT @Findings SELECT N'invalid definition lifecycle/deletion/color/order',COUNT_BIG(*) FROM dbo.OrganizationTypes WHERE SortOrder<0 OR Color<>UPPER(Color) OR Color NOT LIKE N'#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]' OR (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (IsActive<>0 OR DeletedAt IS NULL OR DeletedByUserId IS NULL));
INSERT @Findings SELECT N'invalid assignment lifecycle/deletion/primary/order',COUNT_BIG(*) FROM dbo.OrganizationOrganizationTypes WHERE SortOrder<0 OR (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (IsPrimary<>0 OR DeletedAt IS NULL OR DeletedByUserId IS NULL));
INSERT @Findings SELECT N'missing/disabled/untrusted required CHECK constraints',COUNT_BIG(*) FROM (VALUES
(N'OrganizationTypes',N'CK_OrganizationTypes_SystemKey'),(N'OrganizationTypes',N'CK_OrganizationTypes_Color'),(N'OrganizationTypes',N'CK_OrganizationTypes_SortOrder'),(N'OrganizationTypes',N'CK_OrganizationTypes_DeleteFields'),(N'OrganizationOrganizationTypes',N'CK_OrganizationOrganizationTypes_SortOrder'),(N'OrganizationOrganizationTypes',N'CK_OrganizationOrganizationTypes_DeleteFields'))e(t,n)
LEFT JOIN sys.check_constraints c ON c.parent_object_id=OBJECT_ID(N'dbo.'+e.t) AND c.name=e.n WHERE c.object_id IS NULL OR c.is_disabled=1 OR c.is_not_trusted=1;

DECLARE @Indexes TABLE(t sysname,n sysname,k nvarchar(200),f nvarchar(200),u bit); INSERT @Indexes VALUES
(N'OrganizationTypes',N'UX_OrganizationTypes_Global_SystemKey',N'SystemKey',N'ShaleClientId IS NULL',1),(N'OrganizationTypes',N'UX_OrganizationTypes_Tenant_SystemKey',N'ShaleClientId,SystemKey',N'ShaleClientId IS NOT NULL',1),(N'Organizations',N'UX_Organizations_ShaleClientId_Id',N'ShaleClientId,Id',NULL,1),(N'OrganizationOrganizationTypes',N'UX_OrganizationOrganizationTypes_Active',N'ShaleClientId,OrganizationId,OrganizationTypeId',N'IsDeleted=0',1),(N'OrganizationOrganizationTypes',N'UX_OrganizationOrganizationTypes_ActivePrimary',N'ShaleClientId,OrganizationId',N'IsDeleted=0 AND IsPrimary=1',1),(N'OrganizationOrganizationTypes',N'IX_OrganizationOrganizationTypes_Display',N'ShaleClientId,OrganizationId,IsDeleted,SortOrder,Id',NULL,0);
INSERT @Findings SELECT N'missing/incompatible required indexes',COUNT_BIG(*) FROM @Indexes e OUTER APPLY(SELECT i.*,x.keys FROM sys.indexes i OUTER APPLY(SELECT STRING_AGG(c.name,N',') WITHIN GROUP(ORDER BY ic.key_ordinal) keys FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.is_included_column=0)x WHERE i.object_id=OBJECT_ID(N'dbo.'+e.t) AND i.name=e.n)i WHERE i.index_id IS NULL OR i.is_unique<>e.u OR i.keys<>e.k OR LOWER(REPLACE(REPLACE(ISNULL(i.filter_definition,N''),N'[',N''),N']',N''))<>LOWER(ISNULL(e.f,N''));
INSERT @Findings SELECT N'display Name-only uniqueness remains',COUNT_BIG(*) FROM sys.indexes i WHERE i.object_id=OBJECT_ID(N'dbo.OrganizationTypes') AND i.is_unique=1 AND i.is_primary_key=0 AND (SELECT STRING_AGG(c.name,N',') FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.is_included_column=0)=N'Name';

DECLARE @Fks TABLE(n sysname,ct sysname,cc nvarchar(100),pt sysname,pc nvarchar(100)); INSERT @Fks VALUES
(N'FK_OrganizationType_ShaleClient',N'OrganizationTypes',N'ShaleClientId',N'ShaleClients',N'Id'),
(N'FK_OrganizationTypes_CreatedBy',N'OrganizationTypes',N'CreatedByUserId',N'Users',N'id'),(N'FK_OrganizationTypes_UpdatedBy',N'OrganizationTypes',N'UpdatedByUserId',N'Users',N'id'),(N'FK_OrganizationTypes_DeletedBy',N'OrganizationTypes',N'DeletedByUserId',N'Users',N'id'),
(N'FK_OrganizationOrganizationTypes_Client',N'OrganizationOrganizationTypes',N'ShaleClientId',N'ShaleClients',N'Id'),(N'FK_OrganizationOrganizationTypes_Organization_Tenant',N'OrganizationOrganizationTypes',N'ShaleClientId,OrganizationId',N'Organizations',N'ShaleClientId,Id'),(N'FK_OrganizationOrganizationTypes_Type',N'OrganizationOrganizationTypes',N'OrganizationTypeId',N'OrganizationTypes',N'OrganizationTypeId'),(N'FK_OrganizationOrganizationTypes_CreatedBy',N'OrganizationOrganizationTypes',N'CreatedByUserId',N'Users',N'id'),(N'FK_OrganizationOrganizationTypes_UpdatedBy',N'OrganizationOrganizationTypes',N'UpdatedByUserId',N'Users',N'id'),(N'FK_OrganizationOrganizationTypes_DeletedBy',N'OrganizationOrganizationTypes',N'DeletedByUserId',N'Users',N'id');
INSERT @Findings SELECT N'missing/invalid assignment or actor foreign keys',COUNT_BIG(*) FROM @Fks e OUTER APPLY(SELECT f.object_id,f.is_disabled,f.is_not_trusted,STRING_AGG(pc.name,N',') WITHIN GROUP(ORDER BY fc.constraint_column_id) cc,OBJECT_NAME(f.referenced_object_id) pt,STRING_AGG(rc.name,N',') WITHIN GROUP(ORDER BY fc.constraint_column_id) pc FROM sys.foreign_keys f JOIN sys.foreign_key_columns fc ON fc.constraint_object_id=f.object_id JOIN sys.columns pc ON pc.object_id=fc.parent_object_id AND pc.column_id=fc.parent_column_id JOIN sys.columns rc ON rc.object_id=fc.referenced_object_id AND rc.column_id=fc.referenced_column_id WHERE f.parent_object_id=OBJECT_ID(N'dbo.'+e.ct) AND f.name=e.n GROUP BY f.object_id,f.is_disabled,f.is_not_trusted,f.referenced_object_id)x WHERE x.object_id IS NULL OR x.cc<>e.cc OR x.pt<>e.pt OR x.pc<>e.pc OR x.is_disabled=1 OR x.is_not_trusted=1;

INSERT @Findings SELECT N'duplicate active assignments',COUNT_BIG(*) FROM(SELECT 1 x FROM dbo.OrganizationOrganizationTypes WHERE IsDeleted=0 GROUP BY ShaleClientId,OrganizationId,OrganizationTypeId HAVING COUNT_BIG(*)>1)d;
INSERT @Findings SELECT N'multiple active primary assignments',COUNT_BIG(*) FROM(SELECT 1 x FROM dbo.OrganizationOrganizationTypes WHERE IsDeleted=0 AND IsPrimary=1 GROUP BY ShaleClientId,OrganizationId HAVING COUNT_BIG(*)>1)d;
INSERT @Findings SELECT N'assignment tenant mismatches',COUNT_BIG(*) FROM dbo.OrganizationOrganizationTypes a LEFT JOIN dbo.Organizations o ON o.ShaleClientId=a.ShaleClientId AND o.Id=a.OrganizationId WHERE o.Id IS NULL;
INSERT @Findings SELECT N'definition tenant mismatches',COUNT_BIG(*) FROM dbo.OrganizationOrganizationTypes a JOIN dbo.OrganizationTypes t ON t.OrganizationTypeId=a.OrganizationTypeId WHERE t.ShaleClientId IS NOT NULL AND t.ShaleClientId<>a.ShaleClientId;
INSERT @Findings SELECT N'Organizations missing active primary assignment',COUNT_BIG(*) FROM dbo.Organizations o WHERE NOT EXISTS(SELECT 1 FROM dbo.OrganizationOrganizationTypes a WHERE a.ShaleClientId=o.ShaleClientId AND a.OrganizationId=o.Id AND a.IsDeleted=0 AND a.IsPrimary=1);
INSERT @Findings SELECT N'assignments not matching compatibility OrganizationTypeId',COUNT_BIG(*) FROM dbo.Organizations o LEFT JOIN dbo.OrganizationOrganizationTypes a ON a.ShaleClientId=o.ShaleClientId AND a.OrganizationId=o.Id AND a.OrganizationTypeId=o.OrganizationTypeId AND a.IsDeleted=0 AND a.IsPrimary=1 WHERE a.Id IS NULL;
INSERT @Findings SELECT N'live baseline Organization count changed (expected 176)',ABS(COUNT_BIG(*)-176) FROM dbo.Organizations WHERE ShaleClientId=7;
INSERT @Findings SELECT N'live baseline active/deleted counts changed',CASE WHEN SUM(CASE WHEN IsDeleted=0 THEN 1 ELSE 0 END)=171 AND SUM(CASE WHEN IsDeleted=1 THEN 1 ELSE 0 END)=5 THEN 0 ELSE 1 END FROM dbo.Organizations WHERE ShaleClientId=7;

DECLARE @ExpectedRls TABLE(t sysname,d nvarchar(200)); INSERT @ExpectedRls VALUES(N'OrganizationTypes',N'sec.fn_filterbytenantorglobalshaleclientid'),(N'OrganizationOrganizationTypes',N'sec.fn_filterbytenantshaleclientid');
DECLARE @PolicyId int=(SELECT object_id FROM sys.security_policies WHERE name=N'TenantFilter' AND is_enabled=1);
INSERT @Findings SELECT N'enabled TenantFilter policy count',ABS(COUNT_BIG(*)-1) FROM sys.security_policies WHERE name=N'TenantFilter' AND is_enabled=1;
INSERT @Findings SELECT N'missing/wrong/unexpected RLS predicates',COUNT_BIG(*) FROM @ExpectedRls e WHERE (SELECT COUNT(*) FROM sys.security_predicates sp WHERE sp.object_id=@PolicyId AND sp.target_object_id=OBJECT_ID(N'dbo.'+e.t) AND sp.predicate_type_desc=N'FILTER' AND sp.operation IS NULL AND sp.operation_desc IS NULL AND LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sp.predicate_definition,N'[',N''),N']',N''),N' ',N''),NCHAR(9),N''),NCHAR(10),N''),NCHAR(13),N''),N'(',N''),N')',N''))=e.d)<>1;
INSERT @Findings SELECT N'competing Organization Phase 1A RLS predicates',COUNT_BIG(*) FROM sys.security_predicates sp WHERE sp.target_object_id IN(OBJECT_ID(N'dbo.OrganizationTypes'),OBJECT_ID(N'dbo.OrganizationOrganizationTypes')) AND sp.object_id<>@PolicyId;

SELECT CheckName,FindingCount FROM @Findings ORDER BY CheckName;
IF EXISTS(SELECT 1 FROM @Findings WHERE FindingCount<>0) THROW 57199,'Organizations Phase 1A verification failed; inspect the finding result set.',1;
END TRY BEGIN CATCH THROW; END CATCH;
