/* Read-only Organizations Phase 1A verification. It changes no application table or RLS state. */
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
DECLARE @OperatorVerifiedAllTenantVisibility bit=0;
IF SESSION_CONTEXT(N'ShaleClientId') IS NOT NULL THROW 57100,'Verification requires NULL SESSION_CONTEXT(ShaleClientId).',1;
IF USER_NAME() IN(N'shale_app',N'shale_runtime') OR (ISNULL(IS_SRVROLEMEMBER(N'sysadmin'),0)<>1 AND ISNULL(IS_MEMBER(N'db_owner'),0)<>1) THROW 57101,'Use an approved all-tenant administrative principal.',1;
IF @OperatorVerifiedAllTenantVisibility<>1 THROW 57102,'Acknowledge independently verified all-tenant visibility before verification.',1;
IF OBJECT_ID(N'dbo.OrganizationTypes',N'U') IS NULL OR OBJECT_ID(N'dbo.Organizations',N'U') IS NULL OR OBJECT_ID(N'dbo.OrganizationOrganizationTypes',N'U') IS NULL THROW 57103,'Required Phase 1A table is missing.',1;

DECLARE @Findings TABLE(CheckName nvarchar(200),FindingCount bigint);
/* Exact required column contract; additional columns from later additive phases are allowed. */
INSERT @Findings SELECT N'OrganizationTypes column contract mismatches',COUNT_BIG(*) FROM (VALUES
(N'OrganizationTypeId',N'int',4,0,1,0),(N'Name',N'nvarchar',200,0,0,0),(N'ShaleClientId',N'int',4,1,0,0),(N'SystemKey',N'nvarchar',128,0,0,0),(N'Description',N'nvarchar',1000,1,0,0),(N'Color',N'nvarchar',40,0,0,0),(N'SortOrder',N'int',4,0,0,0),(N'IsActive',N'bit',1,0,0,0),(N'IsDeleted',N'bit',1,0,0,0),(N'CreatedAt',N'datetime2',8,0,0,0),(N'CreatedByUserId',N'int',4,1,0,0),(N'UpdatedAt',N'datetime2',8,1,0,0),(N'UpdatedByUserId',N'int',4,1,0,0),(N'DeletedAt',N'datetime2',8,1,0,0),(N'DeletedByUserId',N'int',4,1,0,0),(N'RowVer',N'timestamp',8,0,0,1))e(n,t,l,z,i,r)
LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.OrganizationTypes') AND c.name=e.n LEFT JOIN sys.types y ON y.user_type_id=c.user_type_id WHERE c.column_id IS NULL OR y.name<>e.t OR c.max_length<>e.l OR c.is_nullable<>e.z OR c.is_identity<>e.i OR (CASE WHEN c.system_type_id=189 THEN 1 ELSE 0 END)<>e.r;
INSERT @Findings SELECT N'assignment column contract mismatches',COUNT_BIG(*) FROM (VALUES
(N'Id',N'bigint',8,0,1,0),(N'ShaleClientId',N'int',4,0,0,0),(N'OrganizationId',N'int',4,0,0,0),(N'OrganizationTypeId',N'int',4,0,0,0),(N'IsPrimary',N'bit',1,0,0,0),(N'SortOrder',N'int',4,0,0,0),(N'IsDeleted',N'bit',1,0,0,0),(N'CreatedAt',N'datetime2',8,0,0,0),(N'CreatedByUserId',N'int',4,1,0,0),(N'UpdatedAt',N'datetime2',8,1,0,0),(N'UpdatedByUserId',N'int',4,1,0,0),(N'DeletedAt',N'datetime2',8,1,0,0),(N'DeletedByUserId',N'int',4,1,0,0),(N'RowVer',N'timestamp',8,0,0,1))e(n,t,l,z,i,r)
LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.OrganizationOrganizationTypes') AND c.name=e.n LEFT JOIN sys.types y ON y.user_type_id=c.user_type_id WHERE c.column_id IS NULL OR y.name<>e.t OR c.max_length<>e.l OR c.is_nullable<>e.z OR c.is_identity<>e.i OR (CASE WHEN c.system_type_id=189 THEN 1 ELSE 0 END)<>e.r;
INSERT @Findings SELECT N'datetime2 precision/scale mismatches',COUNT_BIG(*) FROM sys.columns WHERE object_id IN(OBJECT_ID(N'dbo.OrganizationTypes'),OBJECT_ID(N'dbo.OrganizationOrganizationTypes')) AND name IN(N'CreatedAt',N'UpdatedAt',N'DeletedAt') AND (precision<>27 OR scale<>7);
INSERT @Findings SELECT N'ShaleClientId defaults still present',COUNT_BIG(*) FROM sys.columns c JOIN sys.default_constraints d ON d.object_id=c.default_object_id WHERE c.object_id=OBJECT_ID(N'dbo.OrganizationTypes') AND c.name=N'ShaleClientId';
INSERT @Findings SELECT N'critical default mismatches',COUNT_BIG(*) FROM (VALUES(N'OrganizationTypes',N'SortOrder',N'((0))'),(N'OrganizationTypes',N'IsActive',N'((1))'),(N'OrganizationTypes',N'IsDeleted',N'((0))'),(N'OrganizationTypes',N'CreatedAt',N'(sysutcdatetime())'),(N'OrganizationTypes',N'Color',N'(n''#6c757d'')'),(N'OrganizationOrganizationTypes',N'IsPrimary',N'((0))'),(N'OrganizationOrganizationTypes',N'SortOrder',N'((0))'),(N'OrganizationOrganizationTypes',N'IsDeleted',N'((0))'),(N'OrganizationOrganizationTypes',N'CreatedAt',N'(sysutcdatetime())'))e(t,c,d) LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.'+e.t) AND c.name=e.c LEFT JOIN sys.default_constraints dc ON dc.object_id=c.default_object_id WHERE dc.object_id IS NULL OR LOWER(REPLACE(dc.definition,N' ',N''))<>e.d;

INSERT @Findings SELECT N'unexpected mutation of baseline OrganizationType identity',COUNT_BIG(*) FROM (VALUES(1,N'Provider',7,N'provider'),(2,N'Facility',7,N'facility'),(3,N'Firm',7,N'firm'),(4,N'Agency',7,N'agency'),(5,N'Insurer',7,N'insurer'),(6,N'Lab',7,N'lab'),(7,N'Other',7,N'other'))e(Id,Name,Tenant,SystemKey) LEFT JOIN dbo.OrganizationTypes d ON d.OrganizationTypeId=e.Id WHERE d.OrganizationTypeId IS NULL OR d.Name<>e.Name OR d.ShaleClientId<>e.Tenant OR d.SystemKey<>e.SystemKey;
INSERT @Findings SELECT N'invalid SystemKeys',COUNT_BIG(*) FROM dbo.OrganizationTypes WHERE SystemKey COLLATE Latin1_General_100_BIN2<>LOWER(SystemKey) COLLATE Latin1_General_100_BIN2 OR NULLIF(LTRIM(RTRIM(SystemKey)),N'') IS NULL OR SystemKey COLLATE Latin1_General_100_BIN2 LIKE N'%[^a-z0-9_]%' OR LEFT(SystemKey,1) COLLATE Latin1_General_100_BIN2 NOT LIKE N'[a-z]';
INSERT @Findings SELECT N'duplicate global SystemKeys',COUNT_BIG(*) FROM(SELECT SystemKey FROM dbo.OrganizationTypes WHERE ShaleClientId IS NULL GROUP BY SystemKey HAVING COUNT_BIG(*)>1)x;
INSERT @Findings SELECT N'duplicate tenant SystemKeys',COUNT_BIG(*) FROM(SELECT ShaleClientId,SystemKey FROM dbo.OrganizationTypes WHERE ShaleClientId IS NOT NULL GROUP BY ShaleClientId,SystemKey HAVING COUNT_BIG(*)>1)x;
INSERT @Findings SELECT N'invalid definition lifecycle/deletion/color/order',COUNT_BIG(*) FROM dbo.OrganizationTypes WHERE SortOrder<0 OR DATALENGTH(Color)<>14 OR LEFT(Color,1)<>N'#' OR SUBSTRING(Color,2,6) COLLATE Latin1_General_100_BIN2 LIKE N'%[^0-9A-F]%' OR Color COLLATE Latin1_General_100_BIN2<>UPPER(Color) COLLATE Latin1_General_100_BIN2 OR (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (IsActive<>0 OR DeletedAt IS NULL OR DeletedByUserId IS NULL));
INSERT @Findings SELECT N'invalid assignment lifecycle/deletion/primary/order',COUNT_BIG(*) FROM dbo.OrganizationOrganizationTypes WHERE SortOrder<0 OR (IsDeleted=0 AND (DeletedAt IS NOT NULL OR DeletedByUserId IS NOT NULL)) OR (IsDeleted=1 AND (IsPrimary<>0 OR DeletedAt IS NULL OR DeletedByUserId IS NULL));
DECLARE @Checks TABLE(t sysname,n sysname,d nvarchar(1000)); INSERT @Checks VALUES
(N'OrganizationTypes',N'CK_OrganizationTypes_SystemKey',N'systemkeycollatelatin1_general_100_bin2=lowersystemkeycollatelatin1_general_100_bin2andsystemkey<>n''''andsystemkeycollatelatin1_general_100_bin2notliken''%[^a-z0-9_]%''andleftsystemkey,1collatelatin1_general_100_bin2liken''[a-z]'''),
(N'OrganizationTypes',N'CK_OrganizationTypes_Color',N'datalengthcolor=14andleftcolor,1=n''#''andsubstringcolor,2,6collatelatin1_general_100_bin2notliken''%[^0-9a-f]%''andcolorcollatelatin1_general_100_bin2=uppercolorcollatelatin1_general_100_bin2'),
(N'OrganizationTypes',N'CK_OrganizationTypes_SortOrder',N'sortorder>=0'),
(N'OrganizationTypes',N'CK_OrganizationTypes_DeleteFields',N'isdeleted=0anddeletedatisnullanddeletedbyuseridisnullorisdeleted=1andisactive=0anddeletedatisnotnullanddeletedbyuseridisnotnull'),
(N'OrganizationOrganizationTypes',N'CK_OrganizationOrganizationTypes_SortOrder',N'sortorder>=0'),
(N'OrganizationOrganizationTypes',N'CK_OrganizationOrganizationTypes_DeleteFields',N'isdeleted=0anddeletedatisnullanddeletedbyuseridisnullorisdeleted=1andisprimary=0anddeletedatisnotnullanddeletedbyuseridisnotnull');
INSERT @Findings SELECT N'missing/incompatible required CHECK constraints',COUNT_BIG(*) FROM @Checks e OUTER APPLY(SELECT c.object_id,c.is_disabled,c.is_not_trusted,LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.definition,N'[',N''),N']',N''),N' ',N''),NCHAR(9),N''),NCHAR(10),N''),NCHAR(13),N''),N'(',N''),N')',N'')) d FROM sys.check_constraints c WHERE c.parent_object_id=OBJECT_ID(N'dbo.'+e.t) AND c.name=e.n)c WHERE c.object_id IS NULL OR c.is_disabled=1 OR c.is_not_trusted=1 OR c.d<>e.d;

DECLARE @Indexes TABLE(t sysname,n sysname,k nvarchar(200),f nvarchar(200),u bit); INSERT @Indexes VALUES
(N'OrganizationTypes',N'UX_OrganizationTypes_Global_SystemKey',N'SystemKey',N'shaleclientidisnull',1),(N'OrganizationTypes',N'UX_OrganizationTypes_Tenant_SystemKey',N'ShaleClientId,SystemKey',N'shaleclientidisnotnull',1),(N'Organizations',N'UX_Organizations_ShaleClientId_Id',N'ShaleClientId,Id',N'',1),(N'OrganizationOrganizationTypes',N'UX_OrganizationOrganizationTypes_Active',N'ShaleClientId,OrganizationId,OrganizationTypeId',N'isdeleted=0',1),(N'OrganizationOrganizationTypes',N'UX_OrganizationOrganizationTypes_ActivePrimary',N'ShaleClientId,OrganizationId',N'isdeleted=0andisprimary=1',1),(N'OrganizationOrganizationTypes',N'IX_OrganizationOrganizationTypes_Display',N'ShaleClientId,OrganizationId,IsDeleted,SortOrder,Id',N'',0);
INSERT @Findings SELECT N'missing/incompatible required indexes',COUNT_BIG(*) FROM @Indexes e OUTER APPLY(SELECT i.object_id,i.index_id,i.is_unique,i.has_filter,i.is_disabled,i.is_hypothetical,
 LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL(i.filter_definition,N''),N'[',N''),N']',N''),N' ',N''),NCHAR(9),N''),NCHAR(10),N''),NCHAR(13),N''),N'(',N''),N')',N'')) NormalizedFilter,x.keys,x.includes
 FROM sys.indexes i OUTER APPLY(SELECT STRING_AGG(CASE WHEN ic.key_ordinal>0 THEN c.name END,N',') WITHIN GROUP(ORDER BY ic.key_ordinal) keys,COUNT(CASE WHEN ic.is_included_column=1 THEN 1 END) includes FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id)x WHERE i.object_id=OBJECT_ID(N'dbo.'+e.t) AND i.name=e.n)i
WHERE i.index_id IS NULL OR i.is_unique<>e.u OR i.is_disabled=1 OR i.is_hypothetical=1 OR i.keys<>e.k OR i.includes<>0 OR i.has_filter<>CASE WHEN e.f=N'' THEN 0 ELSE 1 END OR i.NormalizedFilter<>e.f;
INSERT @Findings SELECT N'display Name-only uniqueness remains',COUNT_BIG(*) FROM sys.indexes i WHERE i.object_id=OBJECT_ID(N'dbo.OrganizationTypes') AND i.is_unique=1 AND i.is_primary_key=0 AND (SELECT STRING_AGG(c.name,N',') FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.is_included_column=0)=N'Name';

DECLARE @Fks TABLE(n sysname,ct sysname,cc nvarchar(100),pt sysname,pc nvarchar(100)); INSERT @Fks VALUES
(N'FK_OrganizationType_ShaleClient',N'OrganizationTypes',N'ShaleClientId',N'ShaleClients',N'Id'),
(N'FK_OrganizationTypes_CreatedBy',N'OrganizationTypes',N'CreatedByUserId',N'Users',N'id'),(N'FK_OrganizationTypes_UpdatedBy',N'OrganizationTypes',N'UpdatedByUserId',N'Users',N'id'),(N'FK_OrganizationTypes_DeletedBy',N'OrganizationTypes',N'DeletedByUserId',N'Users',N'id'),
(N'FK_OrganizationOrganizationTypes_Client',N'OrganizationOrganizationTypes',N'ShaleClientId',N'ShaleClients',N'Id'),(N'FK_OrganizationOrganizationTypes_Organization_Tenant',N'OrganizationOrganizationTypes',N'ShaleClientId,OrganizationId',N'Organizations',N'ShaleClientId,Id'),(N'FK_OrganizationOrganizationTypes_Type',N'OrganizationOrganizationTypes',N'OrganizationTypeId',N'OrganizationTypes',N'OrganizationTypeId'),(N'FK_OrganizationOrganizationTypes_CreatedBy',N'OrganizationOrganizationTypes',N'CreatedByUserId',N'Users',N'id'),(N'FK_OrganizationOrganizationTypes_UpdatedBy',N'OrganizationOrganizationTypes',N'UpdatedByUserId',N'Users',N'id'),(N'FK_OrganizationOrganizationTypes_DeletedBy',N'OrganizationOrganizationTypes',N'DeletedByUserId',N'Users',N'id');
INSERT @Findings SELECT N'missing/invalid assignment or actor foreign keys',COUNT_BIG(*) FROM @Fks e OUTER APPLY(SELECT f.object_id,f.is_disabled,f.is_not_trusted,STRING_AGG(pc.name,N',') WITHIN GROUP(ORDER BY fc.constraint_column_id) cc,OBJECT_NAME(f.referenced_object_id) pt,STRING_AGG(rc.name,N',') WITHIN GROUP(ORDER BY fc.constraint_column_id) pc FROM sys.foreign_keys f JOIN sys.foreign_key_columns fc ON fc.constraint_object_id=f.object_id JOIN sys.columns pc ON pc.object_id=fc.parent_object_id AND pc.column_id=fc.parent_column_id JOIN sys.columns rc ON rc.object_id=fc.referenced_object_id AND rc.column_id=fc.referenced_column_id WHERE f.parent_object_id=OBJECT_ID(N'dbo.'+e.ct) AND f.name=e.n GROUP BY f.object_id,f.is_disabled,f.is_not_trusted,f.referenced_object_id)x WHERE x.object_id IS NULL OR x.cc<>e.cc OR x.pt<>e.pt OR x.pc<>e.pc OR x.is_disabled=1 OR x.is_not_trusted=1;

INSERT @Findings SELECT N'duplicate active assignments',COUNT_BIG(*) FROM(SELECT 1 x FROM dbo.OrganizationOrganizationTypes WHERE IsDeleted=0 GROUP BY ShaleClientId,OrganizationId,OrganizationTypeId HAVING COUNT_BIG(*)>1)d;
INSERT @Findings SELECT N'multiple active primary assignments',COUNT_BIG(*) FROM(SELECT 1 x FROM dbo.OrganizationOrganizationTypes WHERE IsDeleted=0 AND IsPrimary=1 GROUP BY ShaleClientId,OrganizationId HAVING COUNT_BIG(*)>1)d;
INSERT @Findings SELECT N'assignment tenant mismatches',COUNT_BIG(*) FROM dbo.OrganizationOrganizationTypes a LEFT JOIN dbo.Organizations o ON o.ShaleClientId=a.ShaleClientId AND o.Id=a.OrganizationId WHERE o.Id IS NULL;
INSERT @Findings SELECT N'definition tenant mismatches',COUNT_BIG(*) FROM dbo.OrganizationOrganizationTypes a JOIN dbo.OrganizationTypes t ON t.OrganizationTypeId=a.OrganizationTypeId WHERE t.ShaleClientId IS NOT NULL AND t.ShaleClientId<>a.ShaleClientId;
INSERT @Findings SELECT N'Organizations missing historical foundation assignment',COUNT_BIG(*) FROM dbo.Organizations o WHERE NOT EXISTS(SELECT 1 FROM dbo.OrganizationOrganizationTypes a WHERE a.ShaleClientId=o.ShaleClientId AND a.OrganizationId=o.Id AND a.OrganizationTypeId=o.OrganizationTypeId);
INSERT @Findings SELECT N'assignments not matching compatibility OrganizationTypeId',COUNT_BIG(*) FROM dbo.Organizations o LEFT JOIN dbo.OrganizationOrganizationTypes a ON a.ShaleClientId=o.ShaleClientId AND a.OrganizationId=o.Id AND a.OrganizationTypeId=o.OrganizationTypeId WHERE a.Id IS NULL;
INSERT @Findings SELECT N'live baseline Organization count changed (expected 176)',ABS(COUNT_BIG(*)-176) FROM dbo.Organizations WHERE ShaleClientId=7;
INSERT @Findings SELECT N'live baseline active/deleted counts changed',CASE WHEN SUM(CASE WHEN IsDeleted=0 THEN 1 ELSE 0 END)=171 AND SUM(CASE WHEN IsDeleted=1 THEN 1 ELSE 0 END)=5 THEN 0 ELSE 1 END FROM dbo.Organizations WHERE ShaleClientId=7;
SELECT N'initial palette/order matches (informational; expected 7 immediately after first deployment)' CheckName,COUNT_BIG(*) MatchingCount FROM (VALUES(1,N'#0F766E',0),(2,N'#2563EB',1),(3,N'#7C3AED',2),(4,N'#D97706',3),(5,N'#059669',4),(6,N'#0891B2',5),(7,N'#6B7280',6))e(Id,Color,SortOrder) JOIN dbo.OrganizationTypes d ON d.OrganizationTypeId=e.Id AND d.Color=e.Color AND d.SortOrder=e.SortOrder;
SELECT N'active primary assignments (informational; expected 176 immediately after first deployment)' CheckName,COUNT_BIG(*) FindingCount FROM dbo.OrganizationOrganizationTypes WHERE IsDeleted=0 AND IsPrimary=1;

DECLARE @ExpectedRls TABLE(t sysname,d nvarchar(200)); INSERT @ExpectedRls VALUES(N'OrganizationTypes',N'sec.fn_filterbytenantorglobalshaleclientid'),(N'OrganizationOrganizationTypes',N'sec.fn_filterbytenantshaleclientid');
DECLARE @PolicyId int=(SELECT object_id FROM sys.security_policies WHERE name=N'TenantFilter' AND is_enabled=1);
INSERT @Findings SELECT N'enabled TenantFilter policy count',ABS(COUNT_BIG(*)-1) FROM sys.security_policies WHERE name=N'TenantFilter' AND is_enabled=1;
INSERT @Findings SELECT N'missing/wrong/unexpected RLS predicates',COUNT_BIG(*) FROM @ExpectedRls e WHERE (SELECT COUNT(*) FROM sys.security_predicates sp WHERE sp.object_id=@PolicyId AND sp.target_object_id=OBJECT_ID(N'dbo.'+e.t) AND sp.predicate_type_desc=N'FILTER' AND sp.operation IS NULL AND sp.operation_desc IS NULL AND LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sp.predicate_definition,N'[',N''),N']',N''),N' ',N''),NCHAR(9),N''),NCHAR(10),N''),NCHAR(13),N''),N'(',N''),N')',N''))=e.d)<>1;
INSERT @Findings SELECT N'competing Organization Phase 1A RLS predicates',COUNT_BIG(*) FROM sys.security_predicates sp WHERE sp.target_object_id IN(OBJECT_ID(N'dbo.OrganizationTypes'),OBJECT_ID(N'dbo.OrganizationOrganizationTypes')) AND sp.object_id<>@PolicyId;

SELECT CheckName,FindingCount FROM @Findings ORDER BY CheckName;
IF EXISTS(SELECT 1 FROM @Findings WHERE FindingCount<>0) THROW 57199,'Organizations Phase 1A verification failed; inspect the finding result set.',1;
END TRY BEGIN CATCH THROW; END CATCH;
