/* Read-only catalog verifier. Every result must report FindingCount = 0. */
SELECT N'TableExists' CheckName,COUNT(*) FindingCount WHERE OBJECT_ID(N'dbo.ApplicationInstances',N'U') IS NULL;
SELECT N'ExactColumns' CheckName,ABS(13-COUNT(*)) FindingCount FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.ApplicationInstances');
SELECT N'RequiredColumnTypes' CheckName,COUNT(*) FindingCount FROM (VALUES(N'Id',N'bigint',0),(N'ShaleClientId',N'int',0),(N'UserId',N'int',0),(N'MachineId',N'uniqueidentifier',1),(N'ClientType',N'varchar',0),(N'MajorVersion',N'int',0),(N'MinorVersion',N'int',0),(N'BuildVersion',N'int',0),(N'StartedAt',N'datetime2',0),(N'EndedAt',N'datetime2',1),(N'CreatedAt',N'datetime2',0),(N'UpdatedAt',N'datetime2',0),(N'RowVer',N'timestamp',0)) e(Name,TypeName,Nullable) LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND c.name=e.Name LEFT JOIN sys.types t ON t.user_type_id=c.user_type_id WHERE c.column_id IS NULL OR t.name<>e.TypeName OR c.is_nullable<>e.Nullable;
SELECT N'PrimaryKey' CheckName,COUNT(*) FindingCount WHERE NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND type='PK');
SELECT N'TrustedTenantUserForeignKey' CheckName,COUNT(*) FindingCount WHERE NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND name=N'FK_ApplicationInstances_UserTenant' AND is_disabled=0 AND is_not_trusted=0 AND delete_referential_action=0);
SELECT N'Checks' CheckName,4-COUNT(*) FindingCount FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND name IN(N'CK_ApplicationInstances_ClientType',N'CK_ApplicationInstances_Machine',N'CK_ApplicationInstances_Version',N'CK_ApplicationInstances_Lifecycle');
SELECT N'Indexes' CheckName,2-COUNT(*) FindingCount FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND name IN(N'IX_ApplicationInstances_TenantUserActive',N'IX_ApplicationInstances_TenantMachine');
SELECT N'RowVersion' CheckName,COUNT(*) FindingCount WHERE NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND name=N'RowVer' AND is_rowguidcol=0 AND system_type_id=189);
SELECT N'StrictRlsPredicateCount' CheckName,ABS(3-COUNT(*)) FindingCount FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.ApplicationInstances');
SELECT N'FilterPredicate' CheckName,COUNT(*) FindingCount WHERE NOT EXISTS(SELECT 1 FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND predicate_type_desc=N'FILTER' AND predicate_definition LIKE N'%fn_FilterByTenant%');
SELECT N'InsertBlockPredicate' CheckName,COUNT(*) FindingCount WHERE NOT EXISTS(SELECT 1 FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND predicate_type_desc=N'BLOCK' AND operation_desc=N'AFTER INSERT');
SELECT N'UpdateBlockPredicate' CheckName,COUNT(*) FindingCount WHERE NOT EXISTS(SELECT 1 FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND predicate_type_desc=N'BLOCK' AND operation_desc=N'AFTER UPDATE');
SELECT N'NoOverlayPredicate' CheckName,COUNT(*) FindingCount FROM sys.security_predicates WHERE target_object_id=OBJECT_ID(N'dbo.ApplicationInstances') AND predicate_definition LIKE N'%OrGlobal%';
SELECT N'NoSeedRows' CheckName,COUNT(*) FindingCount FROM dbo.ApplicationInstances;
SELECT N'PriorPhaseTables' CheckName,COUNT(*) FindingCount FROM (VALUES(N'ApplicationReleases'),(N'ApplicationReleaseItems'),(N'ApplicationPolicy'),(N'UserReleaseState')) e(Name) WHERE OBJECT_ID(N'dbo.'+e.Name,N'U') IS NULL;
