package com.shale.server.controller;
import java.time.Instant;import java.time.format.DateTimeParseException;import java.util.UUID;
import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;
import com.shale.core.model.ClientType;import com.shale.server.dto.*;import com.shale.server.runtime.*;
import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.servlet.http.HttpServletRequest;
@RestController @RequestMapping("/api/admin/sessions") @Tag(name="Session Administration",description="Tenant-admin durable-session inspection and revocation") @SecurityRequirement(name="bearerAuth")
public final class AdminSessionController{
	private final SessionManagementService service;private final ServerRuntimeSessionState state;private final ShaleAuthTokenService tokens;
	public AdminSessionController(SessionManagementService s,ServerRuntimeSessionState state,ShaleAuthTokenService tokens){service=s;this.state=state;this.tokens=tokens;}
	@Operation(summary="List tenant durable sessions") @GetMapping public UserSessionPageResponse list(@RequestParam(name="page",defaultValue="0")int page,@RequestParam(name="size",defaultValue="50")int size,@RequestParam(name="userId",required=false)Integer userId,@RequestParam(name="clientType",required=false)String clientType,@RequestParam(name="activeOnly",defaultValue="false")boolean activeOnly,@RequestParam(name="since",required=false)String since,HttpServletRequest request){try{var items=service.listTenantSessionsAsAdmin(state.requirePrincipal(),sid(request),userId,clientType==null?null:ClientType.valueOf(clientType),activeOnly,since==null?null:Instant.parse(since),page,size);return new UserSessionPageResponse(items,page,size);}catch(IllegalArgumentException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid session filter.");}catch(SecurityException e){throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Administrator access is required.");}}
	@Operation(summary="Revoke a same-tenant durable session") @PostMapping("/{sessionId}/revoke") @ResponseStatus(HttpStatus.NO_CONTENT) public void revoke(@PathVariable(name="sessionId") UUID sessionId,HttpServletRequest request){try{service.revokeTenantSessionAsAdmin(state.requirePrincipal(),sid(request),sessionId);}catch(SecurityException e){throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Administrator access is required.");}}
	private UUID sid(HttpServletRequest r){String raw=BearerTokenServerSessionResolver.bearerToken(r);return tokens.verifyToken(raw).filter(VerifiedAuthToken::isSessionBound).map(VerifiedAuthToken::sessionId).map(UUID::fromString).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"A bound session is required."));}
}
