package com.shale.ui.notification;

public enum NotificationPreferenceKey {
	APP_UPDATES,
	APP_UPDATES_BANNER,
	CONNECTIVITY_STATUS,
	CONNECTIVITY_BANNER,
	TASK_ASSIGNED_TO_ME,
	TASK_DUE_OVERDUE,
	TASK_DUE_OVERDUE_BANNER,
	TASK_DUE_TODAY,
	TASK_DUE_TODAY_BANNER,
	TASK_DUE_TOMORROW,
	CASE_ACTIVITY
}
