package com.shale.core.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;

public record MaterialRequestSummaryDto(long id, int shaleClientId, long caseId, int materialTypeId, String materialTypeName, String materialTypeSystemKey, String materialTypeColor, String title, Integer requestedByUserId, String requestedByDisplayName, String requestedByUserColor, Integer assignedToUserId, String assignedToDisplayName, String assignedToUserColor, Integer requestedFromContactId, String requestedFromContactDisplayName, Integer requestedFromOrganizationId, String requestedFromOrganizationName, String requestedFromText, String requestMethod, LocalDateTime requestedAt, String status, LocalDateTime expectedResponseDate, LocalDateTime nextFollowUpAt, Integer followUpIntervalDays, LocalDateTime lastFollowUpAt, LocalDateTime updatedAt, byte[] rowVer, String description, boolean deleted, LocalDate requestedRangeStartDate, LocalDate requestedRangeEndDate, Integer createdByUserId, String createdByDisplayName) {
    /** Compatibility constructor for callers that predate recurring intervals. */
    public MaterialRequestSummaryDto(long id,int shaleClientId,long caseId,int materialTypeId,String materialTypeName,String materialTypeSystemKey,String materialTypeColor,String title,Integer requestedByUserId,String requestedByDisplayName,String requestedByUserColor,Integer assignedToUserId,String assignedToDisplayName,String assignedToUserColor,Integer requestedFromContactId,String requestedFromContactDisplayName,Integer requestedFromOrganizationId,String requestedFromOrganizationName,String requestedFromText,String requestMethod,LocalDateTime requestedAt,String status,LocalDateTime expectedResponseDate,LocalDateTime nextFollowUpAt,LocalDateTime lastFollowUpAt,LocalDateTime updatedAt,byte[] rowVer){
        this(id,shaleClientId,caseId,materialTypeId,materialTypeName,materialTypeSystemKey,materialTypeColor,title,requestedByUserId,requestedByDisplayName,requestedByUserColor,assignedToUserId,assignedToDisplayName,assignedToUserColor,requestedFromContactId,requestedFromContactDisplayName,requestedFromOrganizationId,requestedFromOrganizationName,requestedFromText,requestMethod,requestedAt,status,expectedResponseDate,nextFollowUpAt,null,lastFollowUpAt,updatedAt,rowVer,null,false,null,null,null,null);
    }

    /** Compatibility constructor for callers that predate requested-range and creator display metadata. */
    public MaterialRequestSummaryDto(long id,int shaleClientId,long caseId,int materialTypeId,String materialTypeName,String materialTypeSystemKey,String materialTypeColor,String title,Integer requestedByUserId,String requestedByDisplayName,String requestedByUserColor,Integer assignedToUserId,String assignedToDisplayName,String assignedToUserColor,Integer requestedFromContactId,String requestedFromContactDisplayName,Integer requestedFromOrganizationId,String requestedFromOrganizationName,String requestedFromText,String requestMethod,LocalDateTime requestedAt,String status,LocalDateTime expectedResponseDate,LocalDateTime nextFollowUpAt,Integer followUpIntervalDays,LocalDateTime lastFollowUpAt,LocalDateTime updatedAt,byte[] rowVer,String description,boolean deleted) {
        this(id,shaleClientId,caseId,materialTypeId,materialTypeName,materialTypeSystemKey,materialTypeColor,title,requestedByUserId,requestedByDisplayName,requestedByUserColor,assignedToUserId,assignedToDisplayName,assignedToUserColor,requestedFromContactId,requestedFromContactDisplayName,requestedFromOrganizationId,requestedFromOrganizationName,requestedFromText,requestMethod,requestedAt,status,expectedResponseDate,nextFollowUpAt,followUpIntervalDays,lastFollowUpAt,updatedAt,rowVer,description,deleted,null,null,null,null);
    }
}
